/*
 * File: app/view/ConfigurarCuentaPanel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.ConfigurarCuentaPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.configurarcuentapanel',

    requires: [
        'Entregas100Web.view.ConfigurarCuentaPanelViewModel',
        'Entregas100Web.view.ConfigurarCuentaPanelViewController',
        'Ext.toolbar.Toolbar',
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.form.field.Text',
        'Ext.form.FieldContainer',
        'Ext.button.Button'
    ],

    controller: 'configurarcuentapanel',
    viewModel: {
        type: 'configurarcuentapanel'
    },
    id: 'configurarCuentaPanel',
    closable: true,
    glyph: 'f013@FontAwesome',
    title: 'Configurar Cuenta',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            height: 45,
            ui: 'footer'
        }
    ],
    items: [
        {
            xtype: 'form',
            frame: true,
            itemId: 'cambiarContrasenaForm',
            width: 450,
            bodyPadding: 10,
            title: 'Cambiar contraseña',
            url: 'api/login/cambiarContrasena',
            items: [
                {
                    xtype: 'hiddenfield',
                    anchor: '100%',
                    name: 'id'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    itemId: 'txtContrasenaActual',
                    fieldLabel: 'Contraseña Actual',
                    labelWidth: 180,
                    name: 'contrasena_actual',
                    inputType: 'password',
                    allowBlank: false,
                    maxLength: 30,
                    minLength: 5,
                    vtype: 'alphanum'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    itemId: 'txtNuevaContrasena',
                    fieldLabel: 'Nueva Contraseña',
                    labelWidth: 180,
                    name: 'contrasena',
                    inputType: 'password',
                    allowBlank: false,
                    maxLength: 30,
                    minLength: 5,
                    vtype: 'alphanum'
                },
                {
                    xtype: 'textfield',
                    validator: function(value) {
                        var nuevaContrasena = this.up("form").down("#txtNuevaContrasena").getValue();

                        if (value != nuevaContrasena) {
                            return "La confirmacion de la contrasena es incorrecta";
                        }

                        return true;
                    },
                    anchor: '100%',
                    itemId: 'txtConfirmacionContrasena',
                    fieldLabel: 'Confirmar Nueva Contraseña',
                    labelWidth: 180,
                    name: 'confirmacion_contrasena',
                    inputType: 'password',
                    allowBlank: false,
                    maxLength: 30,
                    minLength: 5,
                    vtype: 'alphanum'
                },
                {
                    xtype: 'fieldcontainer',
                    margin: '30 0 0 0',
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'btnGuardar',
                            width: 100,
                            glyph: 'f058@FontAwesome',
                            text: 'Guardar',
                            listeners: {
                                click: 'onBtnGuardarClick'
                            }
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onConfigurarCuentaPanelAfterRender'
    }

});