/*
 * File: app/view/CrearScriptRemotoWindowViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.CrearScriptRemotoWindowViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.crearscriptremotowindow',

    onBtnSiguienteClick: function(button, e, eOpts) {
        var me = this,
            txtUnidad = me.view.down("#txtUnidad"),
            txtContenido = me.view.down("#txtContenido"),
            gridScripts = me.view.down("#gridScripts"),
            filename;

        if (!txtUnidad.isValid() || gridScripts.getSelection().length === 0) {
            Ext.Msg.show({
                title: "Mensaje del sistema",
                message: "Es necesario seleccionar una unidad y un script",
                icon: Ext.Msg.ERROR,
                buttons: Ext.Msg.OK
            });

            return;
        }

        me.record.set("filename", "script-remoto-" + Ext.String.leftPad(txtUnidad.getValue(), 3, "0") + ".js");
        txtContenido.setValue(gridScripts.getSelection()[0].get("content"));
        me.view.down("#pnlPaso1").hide();
        me.view.down("#pnlPaso2").show();
    },

    onBtnRegresarClick: function(button, e, eOpts) {
        var me = this;

        Ext.Msg.confirm(
        "Mensaje del sistema",
        "Todos los cambios hechos en su script se perderan. ¿Desea regresar al paso 1?",
        function(result) {
            if (result == "yes") {
                me.view.down("#pnlPaso2").hide();
                me.view.down("#pnlPaso1").show();
            }
        }
        );
    },

    onBtnGuardarClick: function(button, e, eOpts) {
        var me = this,
            store = me.getStore("scriptRemotosStore"),
            txtContenido = me.view.down("#txtContenido"),
            record = me.record;

        Ext.Msg.confirm(
        "Mensaje del sistema",
        "¿Desea crear el guardar y crear el script remoto?",
        function(result) {
            if (result == "yes") {
                record.set("content", txtContenido.getValue());
                record.set(
                "pathname",
                record.get("pathname") + "\\webroot\\js\\" + record.get("filename")
                );
                // se marca como phantom para que se utilice el create en lugar del update al sync el store
                record.phantom = true;
                store.add(record);
                store.sync({
                    success: function() {
                        me.view.destroy();
                        Ext.getCmp("scriptRemotoPanel").down("#btnRefrescar").click();
                    },
                    failure: function(batch) {
                        Ext.Msg.show({
                            title: "Mensaje del sistema",
                            message: "Ha ocurrido un error al crear el script",
                            icon: Ext.Msg.ERROR,
                            buttons: Ext.Msg.OK
                        });
                    }
                });
            }
        }
        );
    }

});
