/*
 * File: app/view/CrearScriptRemotoWindow.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.CrearScriptRemotoWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.crearscriptremotowindow',

    requires: [
        'Entregas100Web.view.CrearScriptRemotoWindowViewModel',
        'Entregas100Web.view.CrearScriptRemotoWindowViewController',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.field.Number',
        'Ext.form.Label',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.view.Table',
        'Ext.form.field.TextArea'
    ],

    controller: 'crearscriptremotowindow',
    viewModel: {
        type: 'crearscriptremotowindow'
    },
    constrain: true,
    modal: true,
    draggable: false,
    height: 600,
    id: 'crearScriptRemotoWindow',
    resizable: false,
    width: 1024,
    layout: 'fit',
    glyph: 'f3b9@PyansaFontAwesomeBrands',
    title: 'Crear script remoto - Paso 1',
    monitorResize: true,

    items: [
        {
            xtype: 'panel',
            itemId: 'pnlPaso1',
            bodyPadding: 20,
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    ui: 'footer',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'btnSiguiente',
                            glyph: 'f0a9@PyansaFontAwesomeSolid',
                            text: 'Siguiente',
                            listeners: {
                                click: 'onBtnSiguienteClick'
                            }
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'numberfield',
                    itemId: 'txtUnidad',
                    fieldLabel: 'Unidad',
                    allowBlank: false,
                    hideTrigger: true,
                    allowDecimals: false
                },
                {
                    xtype: 'label',
                    text: 'Seleccciona un script pre-codificado o uno en blanco'
                },
                {
                    xtype: 'gridpanel',
                    frame: true,
                    height: 400,
                    itemId: 'gridScripts',
                    margin: '10 0 0 0',
                    scrollable: true,
                    autoLoad: true,
                    enableColumnHide: false,
                    enableColumnMove: false,
                    enableColumnResize: false,
                    bind: {
                        store: '{scriptsPrecodificadosStore}'
                    },
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            flex: 1,
                            dataIndex: 'id',
                            text: 'Script'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            hidden: true,
            itemId: 'pnlPaso2',
            layout: 'fit',
            bodyPadding: 20,
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    ui: 'footer',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'btnRegresar',
                            glyph: 'f0a8@PyansaFontAwesomeSolid',
                            text: 'Regresar',
                            listeners: {
                                click: 'onBtnRegresarClick'
                            }
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnGuardar',
                            glyph: 'f058@FontAwesome',
                            text: 'Guardar',
                            listeners: {
                                click: 'onBtnGuardarClick'
                            }
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'textareafield',
                    itemId: 'txtContenido'
                }
            ]
        }
    ]

});