/*
 * File: app/view/CrearDescuentoPromocionWindowViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.CrearDescuentoPromocionWindowViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.creardescuentopromocionwindow',

    onTimeHoraInicialSelect: function(combo, record, eOpts) {
        var me = this,
            cmbHoraFinal = me.view.down("#timeHoraFinal");

        cmbHoraFinal.enable();
        cmbHoraFinal.setMinValue(
        Ext.Date.add(combo.getValue(), Ext.Date.MINUTE, 30)
        );
    },

    onBtnCancelarClick: function(button, e, eOpts) {
        this.view.close();
    },

    onBtnGuardarClick: function(button, e, eOpts) {
        var me = this,
            crearDescuentoPromocionForm = me.view.down("form").getForm(),
            descuentosPromocionPanel = Ext.ComponentManager.get("descuentosPromocionPanel"),
            descuentosPromocionLocalStore = descuentosPromocionPanel.getController().getStore("DescuentosPromocionLocalStore"),
            record, waitWindow;

        if (crearDescuentoPromocionForm.isValid()) {
            waitWindow = Ext.MessageBox.wait("Agregando descuento...");
            record = Ext.create(
            "Entregas100Web.model.DescuentoPromocionModel",
            crearDescuentoPromocionForm.getFieldValues()
            );
            descuentosPromocionLocalStore.add(record);
            descuentosPromocionLocalStore.sync({
                success: onSyncSuccess
            });
        }

        function onSyncSuccess() {
            waitWindow.close();
            me.view.close();
        }
    }

});
