/*
 * File: app/view/CrearUsuarioWindow.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.CrearUsuarioWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.crearusuariowindow',

    requires: [
        'Entregas100Web.view.CrearUsuarioWindowViewModel',
        'Entregas100Web.view.CrearUsuarioWindowViewController',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.FieldContainer',
        'Ext.button.Button',
        'Ext.toolbar.Spacer',
        'Ext.form.field.Hidden'
    ],

    controller: 'crearusuariowindow',
    viewModel: {
        type: 'crearusuariowindow'
    },
    modal: true,
    width: 400,
    glyph: 'f0c0@FontAwesome',
    title: 'Nuevo Usuario',

    items: [
        {
            xtype: 'form',
            trimValues: true,
            itemId: 'crearUsuarioForm',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'textfield',
                    transformToUpper: true,
                    anchor: '100%',
                    fieldLabel: 'Nombre',
                    name: 'nombre',
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    itemId: 'txtEmail',
                    fieldLabel: 'Email',
                    name: 'email',
                    inputType: 'email',
                    allowBlank: false,
                    vtype: 'email',
                    listeners: {
                        change: 'onTxtEmailChange'
                    }
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    itemId: 'txtUsuario',
                    fieldLabel: 'Usuario',
                    name: 'usuario',
                    allowBlank: false,
                    maxLength: 50,
                    minLength: 4
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Contraseña',
                    name: 'password',
                    inputType: 'password',
                    allowBlank: false,
                    maxLength: 20,
                    minLength: 4
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    itemId: 'cmbTipoSesion',
                    fieldLabel: 'Tipo',
                    name: 'tipo_sesion_id',
                    allowBlank: false,
                    editable: false,
                    displayField: 'tipo_sesion',
                    forceSelection: true,
                    valueField: 'id',
                    bind: {
                        store: '{TiposSesionLocalStore}'
                    }
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    itemId: 'cmbPlaza',
                    fieldLabel: 'Plaza',
                    name: 'plaza_id',
                    allowBlank: false,
                    editable: false,
                    displayField: 'ciudad',
                    forceSelection: true,
                    valueField: 'id',
                    bind: {
                        store: '{PlazasLocalStore}'
                    }
                },
                {
                    xtype: 'fieldcontainer',
                    margin: '20 0 0 0',
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'btnCancelar',
                            width: 120,
                            glyph: 'f057@FontAwesome',
                            text: 'Cancelar',
                            listeners: {
                                click: 'onBtnCancelarClick'
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            width: 20
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnGuardar',
                            width: 120,
                            glyph: 'f058@FontAwesome',
                            text: 'Guardar',
                            listeners: {
                                click: 'onBtnGuardarClick'
                            }
                        }
                    ]
                },
                {
                    xtype: 'hiddenfield',
                    anchor: '100%',
                    name: 'estatus',
                    value: true
                }
            ]
        }
    ]

});