/*
 * File: app/view/CrearDescuentoPromocionWindow.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.CrearDescuentoPromocionWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.creardescuentopromocionwindow',

    requires: [
        'Entregas100Web.view.CrearDescuentoPromocionWindowViewModel',
        'Entregas100Web.view.CrearDescuentoPromocionWindowViewController',
        'Ext.form.Panel',
        'Ext.form.field.Number',
        'Ext.form.FieldSet',
        'Ext.form.field.Time',
        'Ext.toolbar.Spacer',
        'Ext.form.FieldContainer',
        'Ext.button.Button'
    ],

    controller: 'creardescuentopromocionwindow',
    viewModel: {
        type: 'creardescuentopromocionwindow'
    },
    modal: true,
    id: 'crearDescuentoPromocionWindow',
    width: 480,
    glyph: 'f4d3@PyansaFontAwesomeSolid',
    title: 'Crear Descuento Promocion',

    items: [
        {
            xtype: 'form',
            itemId: 'crearDescuentoPromocionForm',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'numberfield',
                    anchor: '100%',
                    fieldLabel: 'Descuento',
                    name: 'descuento',
                    allowBlank: false,
                    hideTrigger: true,
                    minValue: 0
                },
                {
                    xtype: 'fieldset',
                    title: 'Rango de horario',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'timefield',
                            flex: 1,
                            itemId: 'timeHoraInicial',
                            fieldLabel: 'Hora inicial',
                            labelWidth: 80,
                            name: 'hora_inicio',
                            allowBlank: false,
                            editable: false,
                            matchFieldWidth: false,
                            forceSelection: true,
                            increment: 30,
                            minValue: '4:00 AM',
                            listeners: {
                                select: 'onTimeHoraInicialSelect'
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            width: 20
                        },
                        {
                            xtype: 'timefield',
                            validator: function(value) {
                                var horaInicial = this.up("form").getForm().getFieldValues().hora_inicio,
                                    horaFinal = this.getValue();

                                if (horaInicial < horaFinal) {
                                    return true;
                                } else {
                                    return "El horario inicial debe ser menor al horario final";
                                }
                            },
                            flex: 1,
                            itemId: 'timeHoraFinal',
                            fieldLabel: 'Hora final',
                            labelWidth: 80,
                            name: 'hora_fin',
                            allowBlank: false,
                            editable: false,
                            matchFieldWidth: false,
                            forceSelection: true,
                            increment: 30
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    title: 'Rango de litraje',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'numberfield',
                            flex: 1,
                            fieldLabel: 'Lts. Minimo',
                            labelWidth: 80,
                            name: 'litros_min',
                            allowBlank: false,
                            hideTrigger: true,
                            minValue: 0
                        },
                        {
                            xtype: 'tbspacer',
                            width: 20
                        },
                        {
                            xtype: 'numberfield',
                            validator: function(value) {
                                var litrosMin = this.up("form").getForm().getFieldValues().litros_min,
                                    litrosMax = this.getValue();

                                if (litrosMin <= litrosMax) {
                                    return true;
                                } else {
                                    return "El litraje maximo debe ser mayor al litraje minimo";
                                }
                            },
                            flex: 1,
                            fieldLabel: 'Lts Maximo',
                            labelWidth: 80,
                            name: 'litros_max',
                            allowBlank: false,
                            hideTrigger: true,
                            allowExponential: false,
                            decimalPrecision: 3,
                            minValue: 0
                        }
                    ]
                },
                {
                    xtype: 'fieldcontainer',
                    margin: '20 0 0 0',
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'btnCancelar',
                            width: 120,
                            glyph: 'f057@FontAwesome',
                            text: 'Cancelar',
                            listeners: {
                                click: 'onBtnCancelarClick'
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            width: 20
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnGuardar',
                            width: 120,
                            glyph: 'f058@FontAwesome',
                            text: 'Guardar',
                            listeners: {
                                click: 'onBtnGuardarClick'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});