/*
 * File: app/view/DescuentosPromocionPanel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.DescuentosPromocionPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.descuentospromocionpanel',

    requires: [
        'Entregas100Web.view.DescuentosPromocionPanelViewModel',
        'Entregas100Web.view.DescuentosPromocionPanelViewController',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.view.Table',
        'Ext.grid.filters.Filters',
        'Ext.grid.column.Date',
        'Ext.grid.column.Action',
        'Pyansa.window.dialog.ComboBox'
    ],

    controller: 'descuentospromocionpanel',
    viewModel: {
        type: 'descuentospromocionpanel'
    },
    id: 'descuentosPromocionPanel',
    closable: true,
    glyph: 'f4d3@PyansaFontAwesomeSolid',
    title: 'Descuentos promocion',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            ui: 'footer',
            items: [
                {
                    xtype: 'button',
                    itemId: 'btnRefrescar',
                    ui: 'default-small',
                    glyph: 'f021@FontAwesome',
                    text: 'Refrescar',
                    listeners: {
                        click: 'onBtnRefrescarClick'
                    }
                },
                {
                    xtype: 'button',
                    permissionId: 47,
                    itemId: 'btnAgregar',
                    glyph: 'f055@FontAwesome',
                    text: 'Agregar',
                    listeners: {
                        click: 'onBtnAgregarClick'
                    }
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            showMenuTriggers: true,
            showMenuHint: true,
            flex: 1,
            itemId: 'descuentosPromocionGrid',
            scrollable: true,
            autoLoad: true,
            columnLines: true,
            enableColumnHide: false,
            enableColumnMove: false,
            bind: {
                store: '{DescuentosPromocionLocalStore}'
            },
            columns: [
                {
                    xtype: 'numbercolumn',
                    width: 110,
                    dataIndex: 'descuento',
                    text: 'Descuento'
                },
                {
                    xtype: 'datecolumn',
                    width: 110,
                    dataIndex: 'hora_inicio',
                    text: 'Hora inicial',
                    format: 'g:i A'
                },
                {
                    xtype: 'datecolumn',
                    width: 100,
                    dataIndex: 'hora_fin',
                    text: 'Hora final',
                    format: 'g:i A'
                },
                {
                    xtype: 'numbercolumn',
                    width: 110,
                    dataIndex: 'litros_min',
                    text: 'Lts. Minimo',
                    format: '0,000.###'
                },
                {
                    xtype: 'numbercolumn',
                    width: 110,
                    dataIndex: 'litros_max',
                    text: 'Lts. Maximo',
                    format: '0,000.###'
                },
                {
                    xtype: 'actioncolumn',
                    permissionId: 48,
                    width: 30,
                    items: [
                        {
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                var editarDescuentoPromocionWindow = Ext.create("Entregas100Web.view.EditarDescuentoPromocionWindow");

                                editarDescuentoPromocionWindow.down("form").loadRecord(record);
                                editarDescuentoPromocionWindow.show();
                            },
                            icon: 'resources/icon/editar.png',
                            tooltip: 'Editar'
                        }
                    ]
                },
                {
                    xtype: 'actioncolumn',
                    permissionId: 49,
                    width: 30,
                    items: [
                        {
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                var descuentosPromocionLocalStore = record.store;

                                Ext.Msg.confirm(
                                "Mensaje del sistema",
                                "¿Desea eliminar el descuento definitivamente?",
                                function(result) {
                                    if (result == "yes") {
                                        descuentosPromocionLocalStore.remove(record);
                                        descuentosPromocionLocalStore.sync();
                                    }
                                }
                                );
                            },
                            icon: 'resources/icon/garbage.png',
                            tooltip: 'Eliminar'
                        }
                    ]
                }
            ],
            viewConfig: {
                emptyText: 'No se encontraron resultados'
            },
            plugins: [
                {
                    ptype: 'gridfilters'
                }
            ]
        }
    ],
    listeners: {
        beforerender: 'onDescuentosPromocionPanelBeforeRender'
    }

});