/*
 * File: app/view/EditarTablaPuntosWindow.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.EditarTablaPuntosWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.editartablapuntoswindow',

    requires: [
        'Entregas100Web.view.EditarTablaPuntosWindowViewModel',
        'Entregas100Web.view.EditarTablaPuntosWindowViewController',
        'Ext.form.Panel',
        'Ext.form.FieldContainer',
        'Ext.form.field.Number',
        'Ext.toolbar.Spacer',
        'Ext.form.FieldSet',
        'Ext.form.field.Time',
        'Ext.button.Button',
        'Ext.form.field.Hidden'
    ],

    controller: 'editartablapuntoswindow',
    viewModel: {
        type: 'editartablapuntoswindow'
    },
    modal: true,
    id: 'editarTablaPuntosWindow',
    width: 480,
    glyph: 'f4b9@PyansaFontAwesomeSolid',
    title: 'Editar Registro de Puntos',

    items: [
        {
            xtype: 'form',
            itemId: 'editarTablaPuntosForm',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'fieldcontainer',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'numberfield',
                            flex: 1,
                            fieldLabel: 'Puntos',
                            labelWidth: 80,
                            name: 'puntos',
                            allowBlank: false,
                            hideTrigger: true,
                            allowDecimals: false,
                            allowExponential: false,
                            minValue: 1
                        },
                        {
                            xtype: 'tbspacer',
                            width: 20
                        },
                        {
                            xtype: 'combobox',
                            flex: 1,
                            itemId: 'cmbPlaza',
                            fieldLabel: 'Plaza',
                            labelWidth: 80,
                            name: 'plaza_id',
                            editable: false,
                            displayField: 'ciudad',
                            forceSelection: true,
                            valueField: 'id',
                            bind: {
                                store: '{PlazasLocalStore}'
                            },
                            listeners: {
                                select: 'onCmbPlazaSelect'
                            }
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    title: 'Rango de horario',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'timefield',
                            flex: 1,
                            itemId: 'timeHoraInicial',
                            fieldLabel: 'Hora inicial',
                            labelWidth: 80,
                            name: 'hora_inicial',
                            allowBlank: false,
                            editable: false,
                            matchFieldWidth: false,
                            forceSelection: true,
                            minValue: '4:00 AM',
                            listeners: {
                                select: 'onTimeHoraInicialSelect'
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            width: 20
                        },
                        {
                            xtype: 'timefield',
                            validator: function(value) {
                                var horaInicial = this.up("form").getForm().getFieldValues().hora_inicial,
                                    horaFinal = this.getValue();

                                if (horaInicial < horaFinal) {
                                    return true;
                                } else {
                                    return "El horario inicial debe ser menor al horario final";
                                }
                            },
                            flex: 1,
                            itemId: 'timeHoraFinal',
                            fieldLabel: 'Hora final',
                            labelWidth: 80,
                            name: 'hora_final',
                            allowBlank: false,
                            editable: false,
                            matchFieldWidth: false,
                            forceSelection: true
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    title: 'Rango de litraje',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'numberfield',
                            flex: 1,
                            fieldLabel: 'Lts. Minimo',
                            labelWidth: 80,
                            name: 'limite_inferior',
                            allowBlank: false,
                            hideTrigger: true,
                            minValue: 0
                        },
                        {
                            xtype: 'tbspacer',
                            width: 20
                        },
                        {
                            xtype: 'numberfield',
                            validator: function(value) {
                                var litrosMin = this.up("form").getForm().getFieldValues().limite_inferior,
                                    litrosMax = this.getValue();

                                if (litrosMin <= litrosMax) {
                                    return true;
                                } else {
                                    return "El litraje maximo debe ser mayor al litraje minimo";
                                }
                            },
                            flex: 1,
                            fieldLabel: 'Lts Maximo',
                            labelWidth: 80,
                            name: 'limite_superior',
                            allowBlank: false,
                            hideTrigger: true,
                            allowExponential: false,
                            decimalPrecision: 3,
                            minValue: 0
                        }
                    ]
                },
                {
                    xtype: 'fieldcontainer',
                    margin: '20 0 0 0',
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'btnCancelar',
                            width: 120,
                            glyph: 'f057@FontAwesome',
                            text: 'Cancelar',
                            listeners: {
                                click: 'onBtnCancelarClick'
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            width: 20
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnGuardar',
                            width: 120,
                            glyph: 'f058@FontAwesome',
                            text: 'Guardar',
                            listeners: {
                                click: 'onBtnGuardarClick'
                            }
                        }
                    ]
                },
                {
                    xtype: 'hiddenfield',
                    anchor: '100%',
                    itemId: 'hidPlaza',
                    fieldLabel: 'Label',
                    name: 'plaza'
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onEditarTablaPuntosWindowAfterRender'
    }

});