/*
 * File: app/view/EditarPlazaWindowViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.EditarPlazaWindowViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.editarplazawindow',

    onBtnCancelarClick: function(button, e, eOpts) {
        this.view.close();
    },

    onBtnGuardarClick: function(button, e, eOpts) {
        var me = this,
            editarPlazaForm = me.view.down("form").getForm(),
            plazasPanel = Ext.ComponentManager.get("plazasPanel"),
            plazasLocalStore = plazasPanel.getController().getStore("PlazasLocalStore"),
            record;

        if (editarPlazaForm.isValid()) {
            waitWindow = Ext.MessageBox.wait("Guardando cambios...");
            editarPlazaForm.updateRecord();
            record = editarPlazaForm.getRecord();

            // si el record no ha sufrigo cambios se termina la edicion
            if (!record.isDirty()) {
                waitWindow.close();
                me.view.close();
                return;
            }

            plazasLocalStore.sync({
                success: onSyncSuccess
            });
        }

        function onSyncSuccess() {
            waitWindow.close();
            me.view.close();
        }
    },

    onEditarPlazaWindowAfterRender: function(component, eOpts) {
        var me = this;

        me.getStore("EmpresasLocalStore").load();
    }

});
