/*
 * File: app/view/EditarOperadorWindowViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.EditarOperadorWindowViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.editaroperadorwindow',

    onBtnCancelarClick: function(button, e, eOpts) {
        this.view.close();
    },

    onBtnGuardarClick: function(button, e, eOpts) {
        var me = this,
            editarOperadorForm = me.view.down("form").getForm(),
            nombrePlaza = me.view.down("#cmbPlaza").getDisplayValue(),
            tipoUsuario = me.view.down("#cmbTipoUsuario").getDisplayValue(),
            operadoresPanel = Ext.ComponentManager.get("operadoresPanel"),
            operadoresLocalStore = operadoresPanel.getController().getStore("OperadoresLocalStore"),
            record, waitWindow;

        if (editarOperadorForm.isValid()) {
            waitWindow = Ext.MessageBox.wait("Guardando cambios...");
            editarOperadorForm.updateRecord();
            record = editarOperadorForm.getRecord();
            record.set("tipo_usuario", tipoUsuario);
            record.set("nombre_plaza", nombrePlaza);
            operadoresLocalStore.sync({
                success: onSyncSuccess
            });
        }

        function onSyncSuccess() {
            waitWindow.close();
            me.view.close();
        }
    },

    onEditarOperadorWindowAfterRender: function(component, eOpts) {
        this.getStore("PlazasLocalStore").load();
    }

});
