/*
 * File: app/view/EditarFormaPagoWindow.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.EditarFormaPagoWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.editarformapagowindow',

    requires: [
        'Entregas100Web.view.EditarFormaPagoWindowViewModel',
        'Entregas100Web.view.EditarFormaPagoWindowViewController',
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.form.field.Text',
        'Ext.form.field.Checkbox',
        'Ext.form.FieldContainer',
        'Ext.button.Button',
        'Ext.toolbar.Spacer'
    ],

    controller: 'editarformapagowindow',
    viewModel: {
        type: 'editarformapagowindow'
    },
    modal: true,
    id: 'editarFormaPagoWindow',
    width: 400,
    glyph: 'f0d6@FontAwesome',
    title: 'Editar Forma de Pago',

    items: [
        {
            xtype: 'form',
            trimValues: true,
            itemId: 'editarFormaPagoForm',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'hiddenfield',
                    anchor: '100%',
                    name: 'id'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Descripcion',
                    name: 'descripcion',
                    allowBlank: false
                },
                {
                    xtype: 'checkboxfield',
                    anchor: '100%',
                    hideEmptyLabel: false,
                    name: 'es_eliminable',
                    boxLabel: 'Es Eliminable'
                },
                {
                    xtype: 'checkboxfield',
                    anchor: '100%',
                    hideEmptyLabel: false,
                    name: 'es_seleccionable',
                    boxLabel: 'Es Seleccionable'
                },
                {
                    xtype: 'fieldcontainer',
                    margin: '20 0 0 0',
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'btnCancelar',
                            width: 120,
                            glyph: 'f057@FontAwesome',
                            text: 'Cancelar',
                            listeners: {
                                click: 'onBtnCancelarClick'
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            width: 20
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnGuardar',
                            width: 120,
                            glyph: 'f058@FontAwesome',
                            text: 'Guardar',
                            listeners: {
                                click: 'onBtnGuardarClick'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});