/*
 * File: app/view/FormasPagoPanel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.FormasPagoPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.formaspagopanel',

    requires: [
        'Entregas100Web.view.FormasPagoPanelViewModel',
        'Entregas100Web.view.FormasPagoPanelViewController',
        'Ext.tab.Panel',
        'Ext.grid.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.grid.column.Number',
        'Ext.grid.filters.filter.String',
        'Ext.grid.column.Boolean',
        'Ext.grid.filters.filter.Boolean',
        'Ext.view.Table',
        'Ext.grid.column.Action',
        'Ext.grid.filters.Filters',
        'Ext.tab.Tab'
    ],

    controller: 'formaspagopanel',
    viewModel: {
        type: 'formaspagopanel'
    },
    id: 'formasPagoPanel',
    layout: 'fit',
    closable: true,
    glyph: 'f0d6@FontAwesome',
    title: 'Formas de Pago',

    items: [
        {
            xtype: 'tabpanel',
            activeTab: 0,
            items: [
                {
                    xtype: 'gridpanel',
                    showMenuTriggers: true,
                    showMenuHint: true,
                    itemId: 'formasPagoGrid',
                    scrollable: true,
                    width: 500,
                    title: 'Formas de Pago',
                    columnLines: true,
                    enableColumnHide: false,
                    enableColumnMove: false,
                    bind: {
                        store: '{FormasPagoLocalStore}'
                    },
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            ui: 'footer',
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'btnRefrescarFormasPago',
                                    glyph: 'f021@FontAwesome',
                                    text: 'Refrescar',
                                    listeners: {
                                        click: 'onBtnRefrescarFormasPagoClick'
                                    }
                                }
                            ]
                        }
                    ],
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            width: 60,
                            dataIndex: 'id',
                            text: 'Id',
                            format: '0,000'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 200,
                            dataIndex: 'descripcion',
                            text: 'Descripción',
                            filter: {
                                type: 'string'
                            }
                        },
                        {
                            xtype: 'booleancolumn',
                            width: 120,
                            dataIndex: 'es_eliminable',
                            text: 'Es eliminable',
                            falseText: 'NO',
                            trueText: 'SI',
                            undefinedText: 'DESCONOCIDO',
                            filter: {
                                type: 'boolean'
                            }
                        },
                        {
                            xtype: 'booleancolumn',
                            width: 140,
                            dataIndex: 'es_seleccionable',
                            text: 'Es seleccionable',
                            falseText: 'NO',
                            trueText: 'SI',
                            undefinedText: 'DESCONOCIDO',
                            filter: {
                                type: 'boolean'
                            }
                        },
                        {
                            xtype: 'numbercolumn',
                            width: 80,
                            dataIndex: 'orden',
                            text: 'Orden',
                            format: '0,000'
                        },
                        {
                            xtype: 'actioncolumn',
                            permissionId: 17,
                            width: 30,
                            items: [
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        var editarFormaPagoWindow = Ext.create("Entregas100Web.view.EditarFormaPagoWindow");

                                        editarFormaPagoWindow.down("form").loadRecord(record);
                                        editarFormaPagoWindow.show();
                                    },
                                    icon: 'resources/icon/editar.png',
                                    tooltip: 'Editar'
                                }
                            ]
                        }
                    ],
                    viewConfig: {
                        emptyText: 'No se encontraron resultados'
                    },
                    plugins: [
                        {
                            ptype: 'gridfilters'
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    itemId: 'combinacionesGrid',
                    title: 'Combinaciones',
                    columnLines: true,
                    enableColumnHide: false,
                    enableColumnMove: false,
                    enableColumnResize: false,
                    sortableColumns: false,
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            ui: 'footer',
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'btnRefrescarCombinaciones',
                                    glyph: 'f021@FontAwesome',
                                    text: 'Refrescar',
                                    listeners: {
                                        click: 'onBtnRefrescarCombinacionesClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnGuardarCombinaciones',
                                    glyph: 'f0c7@FontAwesome',
                                    text: 'Guardar',
                                    listeners: {
                                        click: 'onBtnGuardarCombinacionesClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnRevertirCombinaciones',
                                    glyph: 'f0e2@FontAwesome',
                                    text: 'Revertir',
                                    listeners: {
                                        click: 'onBtnRevertirCombinacionesClick'
                                    }
                                }
                            ]
                        }
                    ],
                    columns: [
                        {
                            xtype: 'booleancolumn',
                            dataIndex: 'descripcion',
                            text: 'Descripcion'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: 'Plazas'
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onFormasPagoPanelAfterRender'
    }

});