/*
 * File: app/view/HorariosZonaPanelViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.HorariosZonaPanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.horarioszonapanel',

    onBtnRefrescarClick: function(button, e, eOpts) {
        this.getStore("HorariosZonaLocalStore").load();
    },

    onBtnAgregarClick: function(button, e, eOpts) {
        var crearHorarioZonaWindow = new Entregas100Web.view.CrearHorarioZonaWindow();

        crearHorarioZonaWindow.show();
    }

});
