/*
 * File: app/view/LoginWindow.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.LoginWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.loginwindow',

    requires: [
        'Entregas100Web.view.LoginWindowViewModel',
        'Entregas100Web.view.LoginWindowViewController',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.form.FieldContainer',
        'Ext.button.Button',
        'Pyansa.overrides.form.field.Text'
    ],

    controller: 'loginwindow',
    viewModel: {
        type: 'loginwindow'
    },
    autoShow: true,
    draggable: false,
    height: 250,
    resizable: false,
    width: 350,
    layout: 'fit',
    closable: false,
    title: 'Iniciar sesión',
    titleAlign: 'center',

    items: [
        {
            xtype: 'form',
            itemId: 'loginForm',
            bodyPadding: 10,
            method: 'POST',
            url: 'api/login/login',
            items: [
                {
                    xtype: 'textfield',
                    trimValue: true,
                    anchor: '100%',
                    fieldLabel: 'Usuario',
                    name: 'usuario',
                    validateOnChange: false,
                    validateOnBlur: false,
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    trimValue: true,
                    anchor: '100%',
                    fieldLabel: 'Contraseña',
                    name: 'contrasena',
                    validateOnChange: false,
                    inputType: 'password',
                    validateOnBlur: false,
                    allowBlank: false
                },
                {
                    xtype: 'fieldcontainer',
                    margin: '30 0 0 0',
                    layout: 'center',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'btnIngresar',
                            ui: 'default-medium',
                            scale: 'medium',
                            text: 'Ingresar',
                            listeners: {
                                click: 'onBtnIngresarClick'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});