/*
 * File: app/view/LoginWindowViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.LoginWindowViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.loginwindow',

    onBtnIngresarClick: function(button, e, eOpts) {
        var me = this,
            loginForm = me.view.down("#loginForm");

        if (loginForm.isValid()) {
            loginForm.submit({
                success: function(form, action) {
                    var mainViewport;

                    Ext._.usuario = action.result.data;
                    // sobreescribe la funcion `isPermited` de Ext.Component.prototype
                    // para aplicarla a todos los componentes
                    Ext.Component.prototype.isPermited = function(permissionId) {
                        return Ext.Array.contains(Ext._.usuario.permisos, permissionId);
                    };

                    mainViewport = new Entregas100Web.view.MainViewport();
                    mainViewport.show();
                    me.view.close();
                },
                failure: function(form, action) {
                    Ext.Msg.show({
                        title: 'Mensaje del Sistema',
                        message: (action.result && action.result.message) || "Error al iniciar sesión",
                        buttons: Ext.Msg.OK,
                        icon: Ext.Msg.ERROR
                    });
                },
                waitMsg: "Validando usuario...",
                waitTitle: "Mensaje del Sistema"
            });
        }
    }

});
