/*
 * File: app/view/MainViewport.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.MainViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainviewport',

    requires: [
        'Entregas100Web.view.MainViewportViewModel',
        'Entregas100Web.view.MainViewportViewController',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.form.field.Display',
        'Ext.tab.Panel',
        'Pyansa.window.dialog.ComboBox'
    ],

    controller: 'mainviewport',
    viewModel: {
        type: 'mainviewport'
    },
    height: 250,
    width: 400,
    layout: 'border',

    items: [
        {
            xtype: 'panel',
            region: 'west',
            frame: true,
            width: 200,
            bodyPadding: 0,
            collapseDirection: 'left',
            collapsible: true,
            title: 'Menu',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    margin: 0,
                    padding: 0,
                    layout: 'accordion',
                    items: [
                        {
                            xtype: 'menu',
                            cls: 'menu-flechas',
                            floating: false,
                            margin: 0,
                            title: 'Configuracion',
                            items: [
                                {
                                    xtype: 'menuitem',
                                    itemId: 'mItemPlazas',
                                    glyph: 'f279@FontAwesome',
                                    text: 'Plazas',
                                    listeners: {
                                        click: 'onMItemPlazasClick'
                                    }
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'mItemFormasPago',
                                    glyph: 'f0d6@FontAwesome',
                                    text: 'Formas de Pago',
                                    listeners: {
                                        click: 'onMItemFormasPagoClick'
                                    }
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'mItemPerfilesPago',
                                    glyph: 'f09d@FontAwesome',
                                    text: 'Perfiles de Pago',
                                    listeners: {
                                        click: 'onMItemPerfilesPagoClick'
                                    }
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'mItemUsuarios',
                                    glyph: 'f0c0@FontAwesome',
                                    text: 'Usuarios',
                                    listeners: {
                                        click: 'onMItemPerfilesPagoClick11'
                                    }
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'mItemPermisos',
                                    glyph: 'f023@FontAwesome',
                                    text: 'Permisos',
                                    listeners: {
                                        click: 'onMItemPerfilesPagoClick1'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'menu',
                            cls: 'menu-flechas',
                            floating: false,
                            margin: 0,
                            title: 'Catalogos',
                            items: [
                                {
                                    xtype: 'menuitem',
                                    itemId: 'mItemZonas',
                                    glyph: 'f041@FontAwesome',
                                    text: 'Zonas',
                                    listeners: {
                                        click: 'onMItemZonasClick'
                                    }
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'mItemUnidades',
                                    glyph: 'f0d1@FontAwesome',
                                    text: 'Unidades',
                                    listeners: {
                                        click: 'onMItemUnidadesClick'
                                    }
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'mItemOperadores',
                                    glyph: 'f0c0@FontAwesome',
                                    text: 'Operadores',
                                    listeners: {
                                        click: 'onMItemOperadoresClick'
                                    }
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'mItemTarifas',
                                    glyph: 'f155@FontAwesome',
                                    text: 'Tarifas',
                                    listeners: {
                                        click: 'onMItemTarifasClick'
                                    }
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'mItemDescuentosPromocion',
                                    glyph: 'f4d3@PyansaFontAwesomeSolid',
                                    text: 'Descuentos promocion',
                                    listeners: {
                                        click: 'onMItemDescuentosPromocionClick'
                                    }
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'mItemHorariosLista',
                                    glyph: 'f017@FontAwesome',
                                    text: 'Horarios de Lista',
                                    listeners: {
                                        click: 'onMItemHorariosListaClick'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'menu',
                            cls: 'menu-flechas',
                            floating: false,
                            margin: 0,
                            title: 'Mi Cuenta',
                            items: [
                                {
                                    xtype: 'menuitem',
                                    itemId: 'mItemConfigurarCuenta',
                                    glyph: 'f013@FontAwesome',
                                    text: 'Configurar cuenta',
                                    listeners: {
                                        click: 'onMItemConfigurarCuentaClick'
                                    }
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'mItemCerrarSesion',
                                    glyph: 'f08b@FontAwesome',
                                    text: 'Cerrar sesion',
                                    listeners: {
                                        click: 'onMItemCerrarSesionClick'
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'displayfield',
                    height: 20,
                    style: 'background: #007888; color: #fff;',
                    fieldLabel: 'Version',
                    labelStyle: 'color: #fff; padding-left: 10px;',
                    value: '2.1',
                    fieldStyle: 'color: #fff;'
                }
            ]
        },
        {
            xtype: 'tabpanel',
            region: 'center',
            itemId: 'tabContainer'
        }
    ]

});