/*
 * File: app/view/ManguerasPanelViewModel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.ManguerasPanelViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.mangueraspanel',

    requires: [
        'Ext.data.Store',
        'Ext.util.Filter',
        'Ext.util.Sorter'
    ],

    stores: {
        localPlazasStore: {
            type: 'mangueras.plazasstore',
            model: 'Entregas100Web.model.mangueras.PlazasModel',
            filters: {
                property: 'estatus',
                value: 1
            },
            sorters: {
                property: 'nom_plaza'
            }
        },
        localRubrosVentasStore: {
            type: 'mangueras.rubrosventasstore',
            model: 'Entregas100Web.model.mangueras.RubrosVentasModel',
            sorters: {
                property: 'nombre'
            }
        }
    }

});