/*
 * File: app/view/ManguerasPanel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.ManguerasPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mangueraspanel',

    requires: [
        'Entregas100Web.view.ManguerasPanelViewModel',
        'Entregas100Web.view.ManguerasPanelViewController',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Action'
    ],

    controller: 'mangueraspanel',
    viewModel: {
        type: 'mangueraspanel'
    },
    flex: 1,
    id: 'mangueraspanel',
    layout: 'fit',
    closable: true,
    glyph: 'f1a4@FontAwesome',
    title: 'Mangueras',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'combobox',
                    itemId: 'cmbPlaza',
                    fieldLabel: 'Plaza',
                    allowBlank: false,
                    displayField: 'nom_plaza',
                    queryMode: 'local',
                    store: 'mangueras.PlazasStore',
                    valueField: 'id_plaza',
                    listeners: {
                        afterrender: 'onCmbPlazaAfterRender'
                    }
                },
                {
                    xtype: 'combobox',
                    itemId: 'cmbRubroVenta',
                    fieldLabel: 'Canal de venta',
                    allowBlank: false,
                    displayField: 'nombre',
                    forceSelection: true,
                    queryMode: 'local',
                    store: 'mangueras.RubrosVentasStore',
                    valueField: 'id_rubro_venta',
                    listeners: {
                        afterrender: 'onCmbRubroVentaAfterRender'
                    }
                },
                {
                    xtype: 'button',
                    itemId: 'btnBuscar',
                    ui: 'default-medium',
                    iconCls: 'x-fa fa-search',
                    scale: 'medium',
                    listeners: {
                        click: 'onBtnBuscarClick'
                    }
                },
                {
                    xtype: 'button',
                    itemId: 'btnExcel',
                    ui: 'default-medium',
                    glyph: 'f1c3@FontAwesome',
                    scale: 'medium',
                    text: 'Excel',
                    listeners: {
                        click: 'onBtnExcelClick'
                    }
                }
            ]
        },
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    itemId: 'btnAgregar',
                    ui: 'default-medium',
                    iconCls: 'x-fa fa-plus',
                    scale: 'medium',
                    tooltip: 'Agregar',
                    listeners: {
                        click: 'onBtnAgregarClick'
                    }
                },
                {
                    xtype: 'button',
                    itemId: 'btnReInsertarInformacion',
                    ui: 'default-medium',
                    scale: 'medium',
                    text: 'Reinsertar información',
                    listeners: {
                        click: 'onBtnInsertarInformacionClick'
                    }
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            showMenuHint: true,
            showMenuTriggers: true,
            frame: true,
            title: '',
            enableColumnHide: false,
            enableColumnMove: false,
            store: 'mangueras.ManguerasStore',
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 138,
                    dataIndex: 'plaza',
                    text: 'Plazas'
                },
                {
                    xtype: 'gridcolumn',
                    width: 273,
                    dataIndex: 'descrip_rubro_venta',
                    text: 'Canal de ventas'
                },
                {
                    xtype: 'gridcolumn',
                    width: 128,
                    dataIndex: 'num_manguera',
                    text: 'Manguera'
                },
                {
                    xtype: 'gridcolumn',
                    width: 233,
                    dataIndex: 'descrip_manguera',
                    text: 'Descripción'
                },
                {
                    xtype: 'gridcolumn',
                    width: 134,
                    dataIndex: 'num_eco',
                    text: 'Num. Economico'
                },
                {
                    xtype: 'gridcolumn',
                    width: 134,
                    dataIndex: 'num_estacion',
                    text: 'Num. Estación'
                },
                {
                    xtype: 'gridcolumn',
                    width: 134,
                    dataIndex: 'num_bascula',
                    text: 'Num. Bascula'
                },
                {
                    xtype: 'gridcolumn',
                    width: 134,
                    dataIndex: 'num_red',
                    text: 'Num. Red'
                },
                {
                    xtype: 'gridcolumn',
                    width: 134,
                    dataIndex: 'sub_red',
                    text: 'Sub red'
                },
                {
                    xtype: 'gridcolumn',
                    width: 134,
                    dataIndex: 'num_bomba',
                    text: 'Num. Bomba'
                },
                {
                    xtype: 'actioncolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        color = "iconDelete";
                        glyph = 'f146@fontAwesome';
                        tooltip = 'Eliminar';
                        this.items[0].tooltip = tooltip;
                        this.items[0].iconCls = color;
                        this.items[0].glyph = glyph;
                        return value;
                    },
                    width: 50,
                    align: 'center',
                    items: [
                        {
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                Ext.Msg.confirm('Mensaje de Sistema','¿Estas segur@ de darlo de Baja?',function(btn){
                                    if(btn === 'yes'){
                                        Ext.MessageBox.show({
                                            title: '<center>Mensaje de Sistema</center>',
                                            msg: '<center>No se puede eliminar, cuenta con estatus activado, verifique porfavor!</center>',
                                            closable:false,
                                            buttons: Ext.Msg.OK,
                                            buttonText:{ok:"Aceptar"},
                                            icon: Ext.Msg.ERROR
                                        });
                                        Ext.Msg.wait('<center>Cargando Información, Espere un momento</center>','<center>Mensaje de Sistema</center>');
                                        var store = Ext.getStore('mangueras.ManguerasStore');
                                        window.store = store;
                                        store.remove(record);
                                        if(store.needsSync){
                                            store.sync({
                                                success: function(batch,options){
                                                    onSyncSucess();
                                                    Ext.MessageBox.show({
                                                        title: '<center>Mensaje de Sistema</center>',
                                                        msg: '<center>Se elimino correctamente!</center>',
                                                        closable:false,
                                                        buttons: Ext.Msg.OK,
                                                        buttonText:{ok:"Aceptar"},
                                                        icon: Ext.MessageBox.INFO
                                                    });
                                                },
                                                failure:function(batch){
                                                    store.rejectChanges();
                                                    Ext.each(batch.exceptions, function(operation){
                                                        if(operation.error.statusText === ""){
                                                            Ext.Msg.hide();
                                                            Ext.MessageBox.show({
                                                                title: '<center>Mensaje de Sistema</center>',
                                                                msg: '<center>Fallo la conexión con el servidor!</center>',
                                                                closable:false,
                                                                buttons: Ext.Msg.OK,
                                                                buttonText:{ok:"Aceptar"},
                                                                icon: Ext.Msg.ERROR
                                                            });
                                                        }else{
                                                            Ext.Msg.hide();
                                                            var error = batch.getExceptions();
                                                            var error1 = error[0].getError();
                                                            Ext.MessageBox.show({
                                                                title: '<center>Mensaje de Sistema</center>',
                                                                msg: '<center>'+error1+'</center>',
                                                                closable:false,
                                                                buttons: Ext.Msg.OK,
                                                                buttonText:{ok:"Aceptar"},
                                                                icon: Ext.Msg.ERROR
                                                            });

                                                        }
                                                    });
                                                }
                                            });
                                        }else{
                                            onSyncSucess();
                                        }
                                    }

                                    function onSyncSucess() {
                                        Ext.Msg.hide();
                                    }
                                });
                            }
                        }
                    ]
                }
            ]
        }
    ]

});