/*
 * File: app/view/OperadoresPanel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.OperadoresPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.operadorespanel',

    requires: [
        'Entregas100Web.view.OperadoresPanelViewModel',
        'Entregas100Web.view.OperadoresPanelViewController',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.grid.Panel',
        'Ext.grid.filters.filter.String',
        'Ext.grid.filters.filter.List',
        'Ext.grid.column.Boolean',
        'Ext.grid.filters.filter.Boolean',
        'Ext.form.field.Checkbox',
        'Ext.view.Table',
        'Ext.grid.column.Action',
        'Ext.grid.filters.Filters',
        'Ext.grid.plugin.RowEditing',
        'Ext.grid.plugin.Exporter'
    ],

    controller: 'operadorespanel',
    viewModel: {
        type: 'operadorespanel'
    },
    id: 'operadoresPanel',
    closable: true,
    glyph: 'f0c0@FontAwesome',
    title: 'Operadores',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            ui: 'footer',
            items: [
                {
                    xtype: 'button',
                    itemId: 'btnRefrescar',
                    ui: 'default-small',
                    glyph: 'f021@FontAwesome',
                    text: 'Refrescar',
                    listeners: {
                        click: 'onBtnRefrescarClick'
                    }
                },
                {
                    xtype: 'button',
                    permissionId: 26,
                    glyph: 'f019@FontAwesome',
                    text: 'Exportar',
                    menu: {
                        xtype: 'menu',
                        width: 120,
                        items: [
                            {
                                xtype: 'menuitem',
                                glyph: 'f1c3@FontAwesome',
                                text: 'Excel',
                                listeners: {
                                    click: 'onMenuitemClick'
                                }
                            }
                        ]
                    }
                },
                {
                    xtype: 'button',
                    permissionId: 11,
                    itemId: 'btnAgregar',
                    glyph: 'f055@FontAwesome',
                    text: 'Agregar',
                    listeners: {
                        click: 'onBtnAgregarClick'
                    }
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            showMenuHint: true,
            showMenuTriggers: true,
            flex: 1,
            itemId: 'operadoresGrid',
            scrollable: true,
            autoLoad: true,
            columnLines: true,
            enableColumnHide: false,
            enableColumnMove: false,
            bind: {
                store: '{OperadoresLocalStore}'
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 300,
                    dataIndex: 'nombre',
                    exportStyle: {
                        width: 400
                    },
                    text: 'Nombre',
                    filter: {
                        type: 'string'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'nip',
                    text: 'NIP',
                    filter: {
                        type: 'string'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    width: 140,
                    dataIndex: 'tipo_usuario',
                    text: 'Tipo de Usuario',
                    filter: {
                        type: 'list'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    width: 140,
                    dataIndex: 'nombre_plaza',
                    text: 'Plaza',
                    filter: {
                        type: 'list'
                    }
                },
                {
                    xtype: 'booleancolumn',
                    width: 130,
                    dataIndex: 'sesion',
                    ignoreExport: true,
                    text: 'Sesion iniciada',
                    falseText: 'NO',
                    trueText: 'SI',
                    undefinedText: 'DESCONOCIDO',
                    filter: {
                        type: 'boolean'
                    },
                    editor: {
                        xtype: 'checkboxfield'
                    }
                },
                {
                    xtype: 'actioncolumn',
                    permissionId: 12,
                    width: 30,
                    ignoreExport: true,
                    items: [
                        {
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                var editarOperadorWindow = Ext.create("Entregas100Web.view.EditarOperadorWindow");

                                editarOperadorWindow.down("form").loadRecord(record);
                                editarOperadorWindow.show();
                            },
                            icon: 'resources/icon/editar.png',
                            tooltip: 'Editar'
                        }
                    ]
                }
            ],
            viewConfig: {
                emptyText: 'No se encontraron resultados'
            },
            plugins: [
                {
                    ptype: 'gridfilters'
                },
                {
                    ptype: 'rowediting',
                    syncAfterEdit: true,
                    listeners: {
                        beforeedit: 'onRowEditingBeforeEdit'
                    }
                },
                {
                    ptype: 'gridexporter'
                }
            ]
        }
    ]

});