/*
 * File: app/view/PermisosPanel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.PermisosPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.permisospanel',

    requires: [
        'Entregas100Web.view.PermisosPanelViewModel',
        'Entregas100Web.view.PermisosPanelViewController',
        'Ext.toolbar.Toolbar',
        'Ext.tab.Panel',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.filters.filter.String',
        'Ext.view.Table',
        'Ext.grid.filters.Filters',
        'Ext.tab.Tab',
        'Ext.grid.filters.filter.List',
        'Ext.grid.column.Check',
        'Ext.grid.feature.Grouping',
        'Ext.XTemplate'
    ],

    controller: 'permisospanel',
    viewModel: {
        type: 'permisospanel'
    },
    id: 'permisosPanel',
    closable: true,
    glyph: 'f023@FontAwesome',
    title: 'Permisos',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            ui: 'footer',
            items: [
                {
                    xtype: 'button',
                    itemId: 'btnRefrescar',
                    ui: 'default-small',
                    glyph: 'f021@FontAwesome',
                    text: 'Refrescar',
                    listeners: {
                        click: 'onBtnRefrescarClick'
                    }
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'tabpanel',
            flex: 1,
            frame: true,
            itemId: 'gridsTabPanel',
            items: [
                {
                    xtype: 'gridpanel',
                    showMenuTriggers: true,
                    showMenuHint: true,
                    itemId: 'tiposSesionGrid',
                    scrollable: true,
                    width: 500,
                    title: 'Permisos por tipo',
                    columnLines: true,
                    enableColumnHide: false,
                    enableColumnMove: false,
                    bind: {
                        store: '{TiposSesionLocalStore}'
                    },
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            width: 60,
                            dataIndex: 'id',
                            text: 'Id',
                            format: '0,000'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 200,
                            dataIndex: 'tipo_sesion',
                            text: 'Tipo',
                            filter: {
                                type: 'string'
                            }
                        }
                    ],
                    viewConfig: {
                        emptyText: 'No se encontraron resultados'
                    },
                    plugins: [
                        {
                            ptype: 'gridfilters'
                        }
                    ],
                    listeners: {
                        select: 'onTiposSesionGridSelect',
                        beforeselect: 'onTiposSesionGridBeforeSelect'
                    }
                },
                {
                    xtype: 'gridpanel',
                    showMenuTriggers: true,
                    showMenuHint: true,
                    itemId: 'usuariosGrid',
                    scrollable: true,
                    width: 500,
                    title: 'Permisos personalizados',
                    columnLines: true,
                    enableColumnHide: false,
                    enableColumnMove: false,
                    bind: {
                        store: '{UsuariosLocalStore}'
                    },
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            width: 60,
                            dataIndex: 'id',
                            text: 'Id',
                            format: '0,000'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 200,
                            dataIndex: 'nombre',
                            text: 'Nombre',
                            filter: {
                                type: 'string'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 120,
                            dataIndex: 'usuario',
                            text: 'Usuario'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 150,
                            dataIndex: 'tipo_sesion',
                            text: 'Tipo',
                            filter: {
                                type: 'list'
                            }
                        }
                    ],
                    viewConfig: {
                        emptyText: 'No se encontraron resultados'
                    },
                    plugins: [
                        {
                            ptype: 'gridfilters'
                        }
                    ],
                    listeners: {
                        select: 'onUsuariosGridSelect',
                        beforeselect: 'onUsuariosGridBeforeSelect'
                    }
                }
            ]
        },
        {
            xtype: 'tabpanel',
            flex: 1,
            frame: true,
            items: [
                {
                    xtype: 'gridpanel',
                    itemId: 'permisosGrid',
                    scrollable: true,
                    title: 'Permisos',
                    enableColumnHide: false,
                    enableColumnMove: false,
                    bind: {
                        store: '{PermisosLocalStore}'
                    },
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            ui: 'footer',
                            items: [
                                {
                                    xtype: 'button',
                                    permissionId: 35,
                                    itemId: 'btnRevertir',
                                    glyph: 'f0e2@FontAwesome',
                                    text: 'Revertir',
                                    tooltip: 'Revertir cambios',
                                    listeners: {
                                        click: 'onBtnRevertirClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    permissionId: 35,
                                    itemId: 'btnGuardar',
                                    glyph: 'f058@FontAwesome',
                                    text: 'Guardar',
                                    tooltip: 'Guardar cambios',
                                    listeners: {
                                        click: 'onBtnGuardarClick'
                                    }
                                }
                            ]
                        }
                    ],
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            width: 60,
                            dataIndex: 'id',
                            text: 'Id',
                            format: '0,000'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 400,
                            dataIndex: 'descripcion',
                            text: 'Permiso'
                        },
                        {
                            xtype: 'checkcolumn',
                            dataIndex: 'es_permitido',
                            tooltip: 'Permitir todo',
                            headerCheckbox: true
                        }
                    ],
                    features: [
                        {
                            ftype: 'grouping',
                            groupHeaderTpl: [
                                '{name}'
                            ],
                            startCollapsed: true
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onPermisosPanelAfterRender'
    }

});