/*
 * File: app/view/ReportesAlarmasPanelViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.ReportesAlarmasPanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.reportesalarmaspanel',

    onBtnRefrescarClick: function(button, e, eOpts) {
        this.getStore("LogsAlarmasLocalStore").load();
    },

    onMItemExportarExcelClick: function(item, e, eOpts) {
        var me = this;

        me.view.down("#logsAlarmasGrid").saveDocumentAs({
            type: "excel",
            title: "Reporte de Alarmas",
            author: "Entregas100",
            fileName: "reporte_alarmas.xlsx",
            includeGroups: true
        });
    },

    onReportesAlarmasPanelBeforeRender: function(component, eOpts) {
        var me = this,
            fechaColumn = me.view.down("#fechaColumn");

        // activa el filtro de fecha con valor de la fecha de ayer
        fechaColumn.filter.filter.eq.setValue(Ext.Date.subtract(new Date(), Ext.Date.DAY, 1));
        fechaColumn.filter.setActive(true);
    }

});
