/*
 * File: app/view/ScriptRemotoPanel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.ScriptRemotoPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.scriptremotopanel',

    requires: [
        'Entregas100Web.view.ScriptRemotoPanelViewModel',
        'Entregas100Web.view.ScriptRemotoPanelViewController',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.view.Table',
        'Ext.grid.column.Action'
    ],

    controller: 'scriptremotopanel',
    viewModel: {
        type: 'scriptremotopanel'
    },
    id: 'scriptRemotoPanel',
    closable: true,
    glyph: 'f3b9@PyansaFontAwesomeBrands',
    title: 'Script remoto',

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            ui: 'footer',
            items: [
                {
                    xtype: 'combobox',
                    itemId: 'cmbVersion',
                    width: 170,
                    fieldLabel: 'Version',
                    labelWidth: 60,
                    allowBlank: false,
                    editable: false,
                    displayField: 'version',
                    forceSelection: true,
                    valueField: 'version',
                    bind: {
                        store: '{versionesStore}'
                    },
                    listeners: {
                        select: 'onCmbVersionSelect'
                    }
                },
                {
                    xtype: 'button',
                    itemId: 'btnRefrescar',
                    glyph: 'f021@FontAwesome',
                    text: 'Refrescar',
                    listeners: {
                        click: 'onBtnRefrescarClick'
                    }
                },
                {
                    xtype: 'button',
                    itemId: 'btnAgregar',
                    glyph: 'f055@FontAwesome',
                    text: 'Agregar',
                    listeners: {
                        click: 'onBtnAgregarClick'
                    }
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            itemId: 'gridScripts',
            bind: {
                store: '{scriptRemotosStore}'
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    flex: 1,
                    dataIndex: 'filename',
                    text: 'Nombre'
                },
                {
                    xtype: 'numbercolumn',
                    width: 150,
                    dataIndex: 'size',
                    text: 'Tamaño (bytes)',
                    format: '0,000'
                },
                {
                    xtype: 'datecolumn',
                    width: 200,
                    dataIndex: 'last_modified',
                    text: 'Ultima modificación',
                    format: 'd/m/Y H:i'
                },
                {
                    xtype: 'actioncolumn',
                    width: 50,
                    items: [
                        {
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                view.lookupController().onScriptRemotoEliminarClick(view, rowIndex, colIndex, item, e, record, row);
                            },
                            icon: 'resources/icon/garbage.png',
                            tooltip: 'Eliminar'
                        }
                    ]
                }
            ]
        }
    ]

});