/*
 * File: app/view/ScriptRemotoPanelViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.ScriptRemotoPanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.scriptremotopanel',

    onScriptRemotoEliminarClick: function(view, rowIndex, colIndex, item, e, record, row) {
        var me = this,
            store = me.getStore("scriptRemotosStore");

        Ext.Msg.confirm(
            "Mensaje del sistema",
            "¿Desea eliminar el script?",
            function(result) {
                if (result == "yes") {
                    store.remove(record);
                    store.sync();
                }
            }
        );
    },

    onCmbVersionSelect: function(combo, record, eOpts) {
        var me = this,
            store = me.getStore("scriptRemotosStore");

        store.removeAll();
        store.commitChanges();
        store.load({
            params: {
                version: record.get("version")
            }
        });
    },

    onBtnRefrescarClick: function(button, e, eOpts) {
        var me = this,
            cmbVersion = me.view.down("#cmbVersion"),
            store = me.getStore("scriptRemotosStore");

        if (cmbVersion.isValid()) {
            store.load({
                params: {
                    version: cmbVersion.getValue()
                }
            });
        }
    },

    onBtnAgregarClick: function(button, e, eOpts) {
        var me = this,
            cmbVersion = me.view.down("#cmbVersion"),
            win;

        if (cmbVersion.isValid()) {
            win = new Entregas100Web.view.CrearScriptRemotoWindow();
            win.lookupController().record = record = new Entregas100Web.model.ScriptRemoto({
                content: "",
                pathname: cmbVersion.getValue()
            });
            win.show();
        }

    }

});
