/*
 * File: app/view/UnidadesPanelViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.UnidadesPanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.unidadespanel',

    onBtnRefrescarClick: function(button, e, eOpts) {
        var me = this;

        me.getStore("UnidadesLocalStore").load();
        me.getStore("OperadoresLocalStore").load();
    },

    onBtnAgregarClick: function(button, e, eOpts) {
        var crearUnidadWindow = new Entregas100Web.view.CrearUnidadWindow();

        crearUnidadWindow.show();
    },

    onUnidadesGridSelect: function(rowmodel, record, index, eOpts) {
        var me = this,
            operadoresLocalStore = me.getStore("OperadoresLocalStore");

        me.getStore("FoliosLocalStore").loadData([record.copy()]);


        operadoresLocalStore.removeFilter("unidad-seleccionada");
        operadoresLocalStore.addFilter([
        {
            id: "unidad-seleccionada",
            filterFn: function(item) {
                return item.get("unidad_id") == record.get("id");
            }
        }
        ]);
    }

});
