/*
 * File: app/view/UsuariosPanel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.UsuariosPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.usuariospanel',

    requires: [
        'Entregas100Web.view.UsuariosPanelViewModel',
        'Entregas100Web.view.UsuariosPanelViewController',
        'Ext.toolbar.Toolbar',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.filters.filter.String',
        'Ext.view.Table',
        'Ext.grid.filters.Filters',
        'Ext.grid.filters.filter.List',
        'Ext.grid.column.Action',
        'Ext.tab.Panel',
        'Ext.tab.Tab'
    ],

    controller: 'usuariospanel',
    viewModel: {
        type: 'usuariospanel'
    },
    id: 'usuariosPanel',
    closable: true,
    glyph: 'f0c0@FontAwesome',
    title: 'Usuarios',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            ui: 'footer',
            items: [
                {
                    xtype: 'button',
                    itemId: 'btnRefrescar',
                    ui: 'default-small',
                    glyph: 'f021@FontAwesome',
                    text: 'Refrescar',
                    listeners: {
                        click: 'onBtnRefrescarClick'
                    }
                },
                {
                    xtype: 'button',
                    permissionId: 26,
                    itemId: 'btnAgregar',
                    glyph: 'f055@FontAwesome',
                    text: 'Agregar',
                    listeners: {
                        click: 'onBtnAgregarClick'
                    }
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            showMenuTriggers: true,
            showMenuHint: true,
            flex: 1,
            itemId: 'usuariosGrid',
            scrollable: true,
            width: 500,
            autoLoad: true,
            columnLines: true,
            enableColumnHide: false,
            enableColumnMove: false,
            bind: {
                store: '{UsuariosLocalStore}'
            },
            columns: [
                {
                    xtype: 'numbercolumn',
                    width: 60,
                    dataIndex: 'id',
                    text: 'Id',
                    format: '0,000'
                },
                {
                    xtype: 'gridcolumn',
                    width: 200,
                    dataIndex: 'nombre',
                    text: 'Nombre',
                    filter: {
                        type: 'string'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    width: 120,
                    dataIndex: 'usuario',
                    text: 'Usuario',
                    filter: {
                        type: 'string'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    width: 150,
                    dataIndex: 'email',
                    text: 'Email',
                    filter: {
                        type: 'string'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    width: 150,
                    dataIndex: 'tipo_sesion',
                    text: 'Tipo',
                    filter: {
                        type: 'list'
                    }
                },
                {
                    xtype: 'actioncolumn',
                    permissionId: 27,
                    width: 30,
                    items: [
                        {
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                var editarUsuarioWindow = Ext.create("Entregas100Web.view.EditarUsuarioWindow");

                                editarUsuarioWindow.down("form").loadRecord(record);
                                editarUsuarioWindow.show();
                            },
                            icon: 'resources/icon/editar.png',
                            tooltip: 'Editar'
                        }
                    ]
                },
                {
                    xtype: 'actioncolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        var actionItem = this.items[0];

                        if (record.get("estatus")) {
                            actionItem.icon = "resources/icon/activo.png";
                            actionItem.tooltip = "Desactivar";
                        } else {
                            actionItem.icon = "resources/icon/inactivo.png";
                            actionItem.tooltip = "Activar";
                        }

                        return value;
                    },
                    permissionId: 28,
                    width: 30,
                    items: [
                        {
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                var isActivo = record.get("estatus");

                                if (isActivo) {
                                    Ext.Msg.confirm(
                                    "Mensaje del sistema",
                                    "¿Desea desactivar el usuario seleccionado?",
                                    function(result) {
                                        if (result == "yes") {
                                            record.set("estatus", false);
                                            record.store.sync();
                                        }
                                    }
                                    );
                                } else {
                                    record.set("estatus", true);
                                    record.store.sync();
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'actioncolumn',
                    permissionId: 29,
                    width: 30,
                    items: [
                        {
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                var isActivo = record.get("estatus"),
                                    usuariosLocalStore = record.store;

                                if (isActivo) {
                                    Ext.Msg.show({
                                        title: 'Mensaje del sistema',
                                        message: "Es necesario desactivar el usuario primero",
                                        buttons: Ext.Msg.OK,
                                        icon: Ext.Msg.ERROR
                                    });
                                } else {
                                    Ext.Msg.confirm(
                                    "Mensaje del sistema",
                                    "¿Desea eliminar el usuario definitivamente?",
                                    function(result) {
                                        if (result == "yes") {
                                            usuariosLocalStore.remove(record);
                                            usuariosLocalStore.sync();
                                        }
                                    }
                                    );
                                }
                            },
                            icon: 'resources/icon/garbage.png',
                            tooltip: 'Eliminar'
                        }
                    ]
                }
            ],
            viewConfig: {
                emptyText: 'No se encontraron resultados'
            },
            plugins: [
                {
                    ptype: 'gridfilters'
                }
            ],
            listeners: {
                select: 'onUsuariosGridSelect'
            }
        },
        {
            xtype: 'tabpanel',
            frame: true,
            width: 500,
            items: [
                {
                    xtype: 'gridpanel',
                    itemId: 'plazasGrid',
                    scrollable: true,
                    title: 'Plazas',
                    autoLoad: true,
                    enableColumnHide: false,
                    enableColumnMove: false,
                    bind: {
                        store: '{PlazasAgregadasLocalStore}'
                    },
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            ui: 'footer',
                            items: [
                                {
                                    xtype: 'button',
                                    permissionId: 30,
                                    itemId: 'btnAgregarPlaza',
                                    glyph: 'f055@FontAwesome',
                                    text: 'Agregar Plaza',
                                    listeners: {
                                        click: 'onBtnAgregarFormaPagoClick'
                                    }
                                }
                            ]
                        }
                    ],
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            width: 60,
                            dataIndex: 'id',
                            text: 'Id',
                            format: '0,000'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 200,
                            dataIndex: 'ciudad',
                            text: 'Plaza'
                        },
                        {
                            xtype: 'actioncolumn',
                            permissionId: 31,
                            width: 30,
                            items: [
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        var me = this.up("#usuariosPanel").getController(),
                                            plazasAgregadasLocalStore = me.getStore("PlazasAgregadasLocalStore"),
                                            usuarioRecord = me.view.down("#usuariosGrid").getSelection()[0],
                                            usuariosLocalStore = me.getStore("UsuariosLocalStore"),
                                            plazasAgregadas, waitWindow;

                                        Ext.Msg.confirm(
                                        "Mensaje del sistema",
                                        "¿Desea eliminar esta plaza del usuario?",
                                        function(result) {
                                            if (result == "yes") {
                                                waitWindow = Ext.Msg.wait("Guardando cambios...");

                                                plazasAgregadas = plazasAgregadasLocalStore.getData().getValues("id", "data");
                                                plazasAgregadas = Ext.Array.remove(plazasAgregadas, record.get("id"));
                                                usuarioRecord.set("plaza_id", plazasAgregadas.join(","));
                                                usuariosLocalStore.sync({
                                                    success: onSyncSuccess
                                                });
                                            }
                                        }
                                        );

                                        function onSyncSuccess() {
                                            waitWindow.close();
                                            me.onUsuariosGridSelect(null, usuarioRecord, null, null);
                                        }
                                    },
                                    icon: 'resources/icon/garbage.png',
                                    tooltip: 'Eliminar esta forma de pago'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        beforerender: 'onUsuariosPanelBeforeRender'
    }

});