/*
 * File: app/view/WindowNewMangueraViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.WindowNewMangueraViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.windownewmanguera',

    onCmbPlazaChange: function(field, newValue, oldValue, eOpts) {
        if(oldValue !== null){
            this.getView().down('form').reset();
        }
        Ext.Msg.wait('<center>Cargando Información, Espere un momento</center>','<center>Mensaje de Sistema</center>');
        var planta = Ext.getStore('PlantasStore');
        planta.load({
            params:{
                plaza_id: newValue
            }, callback:function(){
                var clave = Ext.getStore('maeciasStore');
                clave.load({
                    params:{
                        plaza_id: newValue
                    }, callback:function(){
                        field.up('window').down('#cmbPlanta').setStore(planta);
                        field.up('window').down('#cmbClave').setStore(clave);
                        Ext.Msg.hide();
                    }
                });
            }
        });
    },

    onCmbCanalVentaChange: function(field, newValue, oldValue, eOpts) {
        var plaza_id = this.getView().down('#cmbPlaza').getValue(),
            planta_id = this.getView().down('#cmbPlanta').getValue();
        var descripcion = this.getView().down('#txtDescripcion'),
            descripcion1 = this.getView().down('#descripcion1'),
            text1 = this.getView().down('#text1'),
            num1 = this.getView().down('#num1'),
            text2 = this.getView().down('#text2'),
            num2 = this.getView().down('#num2'),
            num_bascula =  this.getView().down('#txtNumBascula'),
            num_eco = this.getView().down('#txtNumEco'),
            num_estacion = this.getView().down('#txtNumEstacion'),
            num_red = this.getView().down('#txtNumRed'),
            num_bomba = this.getView().down('#txtNumBomba'),
            id_manguera = this.getView().down('#id_manguera'),
            sub_red = this.getView().down('#txtSubRed');

        Ext.Msg.wait('<center>Cargando Información, Espere un momento</center>','<center>Mensaje de Sistema</center>');
        Ext.Ajax.request({
            url: 'api/Mangueras/ultimaManguera',
            params:{
                plaza_id : plaza_id,
                rubro_venta_id: newValue,
                planta_id: planta_id
            },
            headers:{
                Accept: 'application/json, */*'
            },
            success:function(response){
                try{
                    var resp = JSON.parse(response.responseText);
                    Ext.Msg.hide();
                    if(resp.success){
                        ultima_manguera = resp.records[0].ultimo;

                        if(newValue == 1){
                            descripcion.setValue('');
                            text1.setValue('');
                            num1.setValue('');
                            text2.setValue('');
                            num2.setValue('');
                            descripcion1.setHidden(true);
                            descripcion.setHidden(false);
                            num_bascula.setDisabled(false);
                            num_bascula.allowBlank = false;
                            num_eco.setDisabled(true);
                            num_estacion.setDisabled(true);
                            num_red.setDisabled(true);
                            sub_red.setDisabled(true);
                            num_bomba.setDisabled(true);
                        }
                        if(newValue == 2 || newValue == 4){
                            descripcion.setValue('');
                            descripcion.setHidden(true);
                            descripcion1.setHidden(false);
                            num_estacion.setDisabled(false);
                            num_estacion.allowBlank = false;
                            num_bomba.setDisabled(false);
                            num_bomba.allowBlank = false;
                            num_eco.setDisabled(true);
                            num_red.setDisabled(true);
                            sub_red.setDisabled(true);
                            num_bascula.setDisabled(true);
                        }
                        if(newValue == 3){
                            descripcion.setValue('');
                            text1.setValue('');
                            num1.setValue('');
                            text2.setValue('');
                            num2.setValue('');
                            descripcion.setHidden(false);
                            descripcion1.setHidden(true);
                            num_eco.setDisabled(false);
                            num_eco.allowBlank = false;
                            num_bascula.setDisabled(true);
                            num_estacion.setDisabled(true);
                            num_red.setDisabled(true);
                            sub_red.setDisabled(true);
                            num_bomba.setDisabled(true);
                        }
                        if(newValue == 5){
                            descripcion.setValue('');
                            text1.setValue('');
                            num1.setValue('');
                            text2.setValue('');
                            num2.setValue('');
                            descripcion.setHidden(true);
                            descripcion1.setHidden(false);
                            num_red.setDisabled(false);
                            sub_red.setDisabled(false);
                            num_red.allowBlank = false;
                            sub_red.allowBlank = false;
                            num_eco.setDisabled(true);
                            num_bascula.setDisabled(true);
                            num_estacion.setDisabled(true);
                            num_bomba.setDisabled(true);
                            descripcion.setHidden(true);
                        }
                        id_manguera.setValue(ultima_manguera);

                    }else{
                        Ext.MessageBox.show({
                            title: '<center>Mensaje de Sistema</center>',
                            msg: resp.message,
                            icon: Ext.MessageBox.ERROR,
                            buttons: Ext.Msg.OK,
                            buttonText:{ok:"Aceptar"},
                            closable:false
                        });
                    }
                }catch(Exception){
                    Ext.Msg.hide(
                    null,
                    function(){
                        Ext.MessageBox.show({
                            title: '<center>Mensaje de Sistema</center>',
                            msg: Exception,
                            closable:false,
                            buttons: Ext.Msg.OK,
                            buttonText:{ok:"Aceptar"},
                            icon: Ext.Msg.ERROR
                        });
                    }
                    );
                }
            },
            failure:function(response){
                Ext.MessageBox.show({
                    title: '<center>Mensaje de Sistema</center>',
                    msg: '<center>Fallo la conexión al servidor!</center>',
                    icon: Ext.MessageBox.ERROR,
                    buttons: Ext.Msg.OK,
                    buttonText:{ok:"Aceptar"},
                    closable:false
                });
            }
        });
    },

    onTxtNumEcoChange: function(field, newValue, oldValue, eOpts) {
        this.getView().down('#txtNumBascula').setValue('');
        this.getView().down('#txtNumRed').setValue('');
        this.getView().down('#txtSubRed').setValue('');
        this.getView().down('#txtNumBomba').setValue('');
        this.getView().down('#txtDescripcion').setDisabled(false);
        this.getView().down('#text1').setValue('');
        this.getView().down('#num1').setValue('');
        this.getView().down('#text2').setValue('');
        this.getView().down('#num2').setValue('');
        this.getView().down('#txtDescripcion').setValue('Num. Eco. '+newValue);
    },

    onTxtNumEstacionChange: function(field, newValue, oldValue, eOpts) {
        this.getView().down('#txtDescripcion').setValue('');
        // this.getView().down('#descripcion').setDisabled(true);
        // this.getView().down('#descripcion').setHidden(true);
        // this.getView().down('#descripcion1').setHidden(false);
    },

    onTxtNumBasculaChange: function(field, newValue, oldValue, eOpts) {
        this.getView().down('#txtNumEco').setValue('');
        this.getView().down('#txtNumRed').setValue('');
        this.getView().down('#txtSubRed').setValue('');
        this.getView().down('#txtNumBomba').setValue('');
        this.getView().down('#txtNumEstacion').setValue('');
        // this.getView().down('#descripcion').setHidden(false);
        this.getView().down('#txtDescripcion').setDisabled(false);
        // this.getView().down('#descripcion1').setHidden(true);
        this.getView().down('#text1').setValue('');
        this.getView().down('#num1').setValue('');
        this.getView().down('#text2').setValue('');
        this.getView().down('#num2').setValue('');
        this.getView().down('#txtDescripcion').setValue('Bascula '+newValue);
    },

    onTxtNumRedChange: function(field, newValue, oldValue, eOpts) {
        this.getView().down('#txtNumBascula').setValue('');
        this.getView().down('#txtNumEco').setValue('');
        this.getView().down('#txtNumBomba').setValue('');
        this.getView().down('#txtNumEstacion').setValue('');

    },

    onTxtSubRedChange: function(field, newValue, oldValue, eOpts) {
        var num_red = this.getView().down('#txtNumRed').getValue();
        this.getView().down('#txtDescripcion').setValue('');
        this.getView().down('#text1').setValue('Red ');
        this.getView().down('#num1').setValue(num_red);
        this.getView().down('#text2').setValue('Sub_red ');
        this.getView().down('#num2').setValue(newValue);
        // this.getView().down('#descripcion').setValue('Red '+num_red+', Sub_red '+ newValue);
    },

    onTxtNumBombaChange: function(field, newValue, oldValue, eOpts) {
        this.getView().down('#txtNumBascula').setValue('');
        this.getView().down('#txtNumRed').setValue('');
        this.getView().down('#txtSubRed').setValue('');
        this.getView().down('#txtNumEco').setValue('');
        // this.getView().down('#descripcion').setDisabled(false);
        // this.getView().down('#descripcion1').setHidden(false);
        this.getView().down('#txtDescripcion').setValue('');
        this.getView().down('#text1').setValue('Dispensario ');
        this.getView().down('#num1').setValue(newValue.substring(0,1));
        this.getView().down('#text2').setValue('Bomba ');
        this.getView().down('#num2').setValue(newValue);
        // this.getView().down('#descripcion').setValue('Dispensario '+newValue.substring(0,1)+', Bomba '+newValue);
    },

    onBtnGuardarClick: function(button, e, eOpts) {
        var win =  button.up('window'),
            form   = win.down('form'),
            record = form.getRecord(),
            values = form.getValues();

        var desc = this.getView().down('#descripcion1'),
            txt1 = this.getView().down('#text1').getValue(),
            num1 = this.getView().down('#num1').getValue(),
            txt2 = this.getView().down('#text2').getValue(),
            num2 = this.getView().down('#num2').getValue(),
            descripcion = txt1.concat(' '+num1+', '+txt2+' '+num2);

        Ext.each(desc.items.items,function(child){
            if(child.value !== ""){
                values['descrip_manguera'] = descripcion;
            }
        });

        var plaza = this.getView().down('#cmbPlaza').selection.data.plaza,
            rubro_venta = this.getView().down('#cmbCanalVenta').selection.data.rubro_venta,
            descrip_rubro_venta = this.getView().down('#cmbCanalVenta').rawValue,
            planta = this.getView().down('#cmbPlanta').rawValue,
            num_manguera = this.getView().down('#id_manguera').getValue(),
            clave = this.getView().down('#cmbClave').selection.data.cvecia;


        if(form.isValid()){
            Ext.Msg.wait('<center>Procesando Información, Espere un momento</center>','<center>Mensaje de Sistema</center>');

            var record = Ext.create('Entregas100Web.model.mangueras.PlazasModel');
            record.set(values);
            record.set('plaza', plaza);
            record.set('descrip_rubro_venta', descrip_rubro_venta);
            record.set('rubro_venta', rubro_venta);
            record.set('nombre_planta',planta);
            record.set('cvecia', clave);
            window.store = store;
            var store = Ext.getStore('mangueras.ManguerasStore');
            store.add(record);
            if(store.needsSync){
                store.sync({
                    success: function(batch,options){
                        onSyncSucess();
                        Ext.MessageBox.show({
                            title: '<center>Mensaje de Sistema</center>',
                            msg: '<center>Se agrego correctamente!</center>',
                            closable:false,
                            buttons: Ext.Msg.OK,
                            buttonText:{ok:"Aceptar"},
                            icon: Ext.MessageBox.INFO
                        });

                    },
                    failure:function(batch){
                        store.rejectChanges();
                        Ext.each(batch.exceptions, function(operation){
                            if(operation.error.statusText === ""){
                                Ext.Msg.hide();
                                Ext.MessageBox.show({
                                    title: '<center>Mensaje de Sistema</center>',
                                    msg: '<center>Fallo la conexión con el servidor!</center>',
                                    closable:false,
                                    buttons: Ext.Msg.OK,
                                    buttonText:{ok:"Aceptar"},
                                    icon: Ext.Msg.ERROR
                                });
                            }else{
                                Ext.Msg.hide();
                                var error = batch.getExceptions();
                                var error1 = error[0].getError();
                                Ext.MessageBox.show({
                                    title: '<center>Mensaje de Sistema</center>',
                                    msg: '<center>'+error1+'</center>',
                                    closable:false,
                                    buttons: Ext.Msg.OK,
                                    buttonText:{ok:"Aceptar"},
                                    icon: Ext.Msg.ERROR
                                });
                            }
                        });
                    }
                });
            }else{
                onSyncSucess();
            }
        }else{
            console.log('entro');
            Ext.MessageBox.show({
                title: '<center>Mensaje de Sistema</center>',
                msg: '<center>¡Captura los campos que son requeridos!</center>',
                closable:false,
                buttons: Ext.Msg.OK,
                buttonText:{ok:"Aceptar"},
                icon: Ext.Msg.ERROR
            });
        }

        function onSyncSucess() {
            Ext.Msg.hide();
            win.close();
        }
    },

    onBtnSalirClick: function(button, e, eOpts) {
        this.view.close();
    }

});
