/*
 * File: app/view/windowEditManguera.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.windowEditManguera', {
    extend: 'Ext.window.Window',
    alias: 'widget.windoweditmanguera',

    requires: [
        'Entregas100Web.view.windowEditMangueraViewModel',
        'Entregas100Web.view.windowEditMangueraViewController',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Spacer',
        'Ext.button.Button'
    ],

    controller: 'windoweditmanguera',
    viewModel: {
        type: 'windoweditmanguera'
    },
    modal: true,
    height: 264,
    resizable: false,
    width: 400,
    title: 'Editar mangueras',

    items: [
        {
            xtype: 'form',
            bodyPadding: 10,
            title: '',
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Num Estación',
                    name: 'num_estacion',
                    editable: false
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    itemId: 'txtPermiso',
                    fieldLabel: 'Permiso',
                    name: 'permiso',
                    listeners: {
                        focusleave: 'onTextfieldFocusleave'
                    }
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Nombre estación',
                    name: 'nom_estac',
                    editable: false
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'tbspacer',
                            flex: 1
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            itemId: 'btnGuardar',
                            ui: 'default-medium',
                            glyph: 'f058@FontAwesome',
                            scale: 'medium',
                            text: 'Guardar',
                            tooltip: 'Guardar',
                            listeners: {
                                click: 'onBtnGuardarClick'
                            }
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnSalir',
                            ui: 'default-medium',
                            glyph: 'f057@FontAwesome',
                            scale: 'medium',
                            text: 'Salir',
                            tooltip: 'Salir',
                            listeners: {
                                click: 'onBtnSalirClick'
                            }
                        },
                        {
                            xtype: 'tbspacer',
                            flex: 1
                        }
                    ]
                }
            ]
        }
    ]

});