/*
 * File: app/view/windowNewPermisosViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.windowNewPermisosViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.windownewpermisos',

    onTxtEstaPlantaChange: function(field, newValue, oldValue, eOpts) {
        if(newValue == 4){
            var valor = 'E';
            this.getView().down('#txtEstacionPlanta').setValue('');
            this.getView().down('#txtEstacionPlanta').setEditable(true);
            this.getView().down('#txtEstacionPlanta').allowBlank = false;
            this.getView().down('#txtPermiso').setValue('');
            this.getView().down('#txtPlaEst').setValue(valor);

        }else{
            var valor = 'P';
            this.getView().down('#txtPermiso').setValue('');
            this.getView().down('#txtPlaEst').setValue(valor);
            this.getView().down('#txtEstacionPlanta').allowBlank = true;
        }
    },

    onBtnGuardarClick: function(button, e, eOpts) {
        var win =  button.up('window'),
            form   = win.down('form'),
            record = form.getRecord(),
            values = form.getValues();

        if(form.isValid()){
            Ext.Msg.wait('<center>Procesando Información, Espere un momento</center>','<center>Mensaje de Sistema</center>');

            var store = Ext.getStore('mangueras.PermisosStore');
            store.add({
                permiso: values.permiso,
                plaza_id: values.plaza_id,
                cvecia: values.cvecia,
                pla_est: values.pla_est,
                planta_id: values.planta_id,
                num_estac: values.num_estac,
                tiene_perm: values.tiene_perm,
                nompla_est: values.nompla_est,
                plaza: values.plaza,
                id:1
            });
            onSyncSucess();
            Ext.MessageBox.show({
                title: '<center>Mensaje de Sistema</center>',
                msg: '<center>Se agrego correctamente!</center>',
                closable:false,
                buttons: Ext.Msg.OK,
                buttonText:{ok:"Aceptar"},
                icon: Ext.MessageBox.INFO
            });

        }else{
            Ext.MessageBox.show({
                title: '<center>Mensaje de Sistema</center>',
                msg: '<center>¡Captura los campos que son requeridos!</center>',
                closable:false,
                buttons: Ext.Msg.OK,
                buttonText:{ok:"Aceptar"},
                icon: Ext.Msg.ERROR
            });
        }

        function onSyncSucess() {
            Ext.getCmp('txtPermisoManguera').setValue(values.permiso);
            Ext.Msg.hide();
            win.close();
        }
    },

    onBtnSalirClick: function(button, e, eOpts) {
        this.view.close();
    }

});
