/*
 * File: app/view/WindowNewMangueraViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.WindowNewMangueraViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.windownewmanguera',

    onCmbPlazaChange: function(field, newValue, oldValue, eOpts) {
        if(oldValue !== null){
            this.getView().down('form').reset();
        }
        Ext.Msg.wait('<center>Cargando Información, Espere un momento</center>','<center>Mensaje de Sistema</center>');
        var planta = Ext.getStore('PlantasStore');
        planta.load({
            params:{
                plaza_id: newValue
            }, callback:function(){
                var clave = Ext.getStore('maeciasStore');
                clave.load({
                    params:{
                        plaza_id: newValue
                    }, callback:function(){
                        field.up('window').down('#cmbPlanta').setStore(planta);
                        field.up('window').down('#cmbClave').setStore(clave);
                        Ext.Msg.hide();
                    }
                });
            }
        });
    },

    onCmbClaveChange: function(field, newValue, oldValue, eOpts) {
        this.getView().down('#cmbCanalVenta').setDisabled(false);
    },

    onCmbCanalVentaChange: function(field, newValue, oldValue, eOpts) {
        var plaza_id = this.getView().down('#cmbPlaza').getValue(),
            planta_id = this.getView().down('#cmbPlanta').getValue();
        var descripcion = this.getView().down('#txtDescripcion'),
            descripcion1 = this.getView().down('#descripcion1'),
            text1 = this.getView().down('#text1'),
            num1 = this.getView().down('#num1'),
            text2 = this.getView().down('#text2'),
            num2 = this.getView().down('#num2'),
            num_bascula =  this.getView().down('#txtNumBascula'),
            num_eco = this.getView().down('#txtNumEco'),
            num_estacion = this.getView().down('#txtNumEstacion'),
            permiso = this.getView().down('#cmbPermisoManguera'),
            num_red = this.getView().down('#txtNumRed'),
            num_bomba = this.getView().down('#txtNumBomba'),
            id_manguera = this.getView().down('#id_manguera'),
            sub_red = this.getView().down('#txtSubRed'),
            nombre_estacion = this.getView().down('#txtNombreEstacion'),
            btnAgregarPermiso = this.getView().down('#btnAddPermiso');

        Ext.Msg.wait('<center>Cargando Información, Espere un momento</center>','<center>Mensaje de Sistema</center>');
        Ext.Ajax.request({
            url: 'api/Mangueras/ultimaManguera',
            params:{
                plaza_id : plaza_id,
                rubro_venta_id: newValue,
                planta_id: planta_id
            },
            headers:{
                Accept: 'application/json, */*'
            },
            success:function(response){
                try{
                    var resp = JSON.parse(response.responseText);
                    Ext.Msg.hide();
                    if(resp.success){
                        ultima_manguera = resp.records[0].ultimo;

                        if(newValue == 1){
                            descripcion.setValue('');
                            text1.setValue('');
                            num1.setValue('');
                            text2.setValue('');
                            num2.setValue('');
                            descripcion1.setHidden(true);
                            descripcion.setHidden(false);
                            num_bascula.setDisabled(false);
                            num_bascula.allowBlank = false;
                            num_eco.setDisabled(true);
                            num_estacion.setDisabled(true);
                            permiso.setDisabled(true);
                            num_red.setDisabled(true);
                            sub_red.setDisabled(true);
                            num_bomba.setDisabled(true);
                            nombre_estacion.setDisabled(true);
                            btnAgregarPermiso.setDisabled(true);
                        }
                        if(newValue == 2 || newValue == 4){
                            descripcion.setValue('');
                            descripcion.setHidden(true);
                            descripcion1.setHidden(false);
                            num_estacion.setDisabled(false);
                            num_estacion.allowBlank = false;
                            num_bomba.setDisabled(false);
                            num_bomba.allowBlank = false;
                            num_eco.setDisabled(true);
                            num_red.setDisabled(true);
                            sub_red.setDisabled(true);
                            num_bascula.setDisabled(true);
                            num_bascula.allowBlank = false;
                        }
                        if(newValue == 3){
                            descripcion.setValue('');
                            text1.setValue('');
                            num1.setValue('');
                            text2.setValue('');
                            num2.setValue('');
                            descripcion.setHidden(false);
                            descripcion1.setHidden(true);
                            num_eco.setDisabled(false);
                            num_eco.allowBlank = false;
                            permiso.setDisabled(true);
                            num_bascula.setDisabled(true);
                            num_estacion.setDisabled(true);
                            num_red.setDisabled(true);
                            sub_red.setDisabled(true);
                            num_bomba.setDisabled(true);
                            nombre_estacion.setDisabled(true);
                            btnAgregarPermiso.setDisabled(true);
                        }
                        if(newValue == 5){
                            descripcion.setValue('');
                            text1.setValue('');
                            num1.setValue('');
                            text2.setValue('');
                            num2.setValue('');
                            descripcion.setHidden(true);
                            descripcion1.setHidden(false);
                            num_red.setDisabled(false);
                            sub_red.setDisabled(false);
                            num_red.allowBlank = false;
                            sub_red.allowBlank = false;
                            num_eco.setDisabled(true);
                            permiso.setDisabled(true);
                            num_bascula.setDisabled(true);
                            num_estacion.setDisabled(true);
                            num_bomba.setDisabled(true);
                            descripcion.setHidden(true);
                            nombre_estacion.setDisabled(true);
                            tnAgregarPermiso.setDisabled(true);
                        }
                        id_manguera.setValue(ultima_manguera);

                    }else{
                        Ext.MessageBox.show({
                            title: '<center>Mensaje de Sistema</center>',
                            msg: resp.message,
                            icon: Ext.MessageBox.ERROR,
                            buttons: Ext.Msg.OK,
                            buttonText:{ok:"Aceptar"},
                            closable:false
                        });
                    }
                }catch(Exception){
                    Ext.Msg.hide(
                    null,
                    function(){
                        Ext.MessageBox.show({
                            title: '<center>Mensaje de Sistema</center>',
                            msg: Exception,
                            closable:false,
                            buttons: Ext.Msg.OK,
                            buttonText:{ok:"Aceptar"},
                            icon: Ext.Msg.ERROR
                        });
                    }
                    );
                }
            },
            failure:function(response){
                Ext.MessageBox.show({
                    title: '<center>Mensaje de Sistema</center>',
                    msg: '<center>Fallo la conexión al servidor!</center>',
                    icon: Ext.MessageBox.ERROR,
                    buttons: Ext.Msg.OK,
                    buttonText:{ok:"Aceptar"},
                    closable:false
                });
            }
        });
    },

    onTxtNumEcoChange: function(field, newValue, oldValue, eOpts) {
        this.getView().down('#txtNumBascula').setValue('');
        this.getView().down('#txtNumEstacion').setValue('');
        this.getView().down('#txtNombreEstacion').setValue('');
        this.getView().down('#txtNombreEstacion').setDisabled(true);
        this.getView().down('#txtNombreEstacion').allowBlank = true;
        this.getView().down('#cmbPermisoManguera').setValue('');
        this.getView().down('#cmbPermisoManguera').allowBlank = true;
        this.getView().down('#btnAddPermiso').setDisabled(true);
        this.getView().down('#txtNumRed').setValue('');
        this.getView().down('#txtSubRed').setValue('');
        this.getView().down('#txtNumBomba').setValue('');
        this.getView().down('#txtDescripcion').setDisabled(false);
        this.getView().down('#text1').setValue('');
        this.getView().down('#num1').setValue('');
        this.getView().down('#text2').setValue('');
        this.getView().down('#num2').setValue('');
        this.getView().down('#txtDescripcion').setValue('Num. Eco. '+newValue);
    },

    onTxtNumEstacionChange: function(field, newValue, oldValue, eOpts) {
        this.getView().down('#txtNumEco').setValue('');
        this.getView().down('#txtNumEco').allowBlank = true;
        this.getView().down('#txtNumBascula').setValue('');
        this.getView().down('#txtNumBascula').allowBlank = true;
        this.getView().down('#txtNumRed').setValue('');
        this.getView().down('#txtNumRed').allowBlank = true;
        this.getView().down('#txtSubRed').setValue('');
        this.getView().down('#txtSubRed').allowBlank = true;
        this.getView().down('#txtNumBomba').setValue('');
        this.getView().down('#txtNumBomba').allowBlank = true;
        this.getView().down('#txtNumBomba').setValue('');
        this.getView().down('#txtNumBomba').allowBlank = true;


        this.getView().down('#txtDescripcion').setValue('');
        this.getView().down('#text1').setValue('');
        this.getView().down('#num1').setValue('');
        this.getView().down('#text2').setValue('');
        this.getView().down('#num2').setValue('');
    },

    onTxtNumEstacionFocusleave: function(component, event, eOpts) {
        var planta_id = this.getView().down('#cmbPlanta').getValue(),
            cmbPermiso = this.getView().down('#cmbPermisoManguera'),
            btnAgregarPermiso = this.getView().down('#btnAddPermiso'),
            nombreEstacion = this.getView().down('#txtNombreEstacion'),
            tienePerm = this.getView().down('#txtTienePerm'),
            txtEstacionExiste = this.getView().down('#txtEstacionExiste');

        Ext.Msg.wait('<center>Cargando Información, Espere un momento</center>','<center>Mensaje de Sistema</center>');
        Ext.Ajax.request({
            url: 'api/Mangueras/searchNumEstacion',
            params:{
                num_estacion: component.value
            },
            headers:{
                Accept: 'application/json, */*'
            },
            success:function(response){
                try{
                    var resp = JSON.parse(response.responseText);
                    Ext.Msg.hide();
                    if(resp.success){
                        txtEstacionExiste.setDisabled(false);
                        txtEstacionExiste.setValue('1');
                        nombreEstacion.setDisabled(false);
                        nombreEstacion.setEditable(false);
                        nombreEstacion.setValue(resp.records[0].nom_estac);
                        if(resp.records[0].tiene_perm === 1){
                            tienePerm.setDisabled(false);
                            tienePerm.setValue('1');
                        }
                    }else{
                        txtEstacionExiste.setDisabled(true);
                        Ext.Msg.confirm('Mensaje de Sistema','¿La Estación cuenta con permiso propio?',function(btn){
                            if(btn === 'yes'){
                                cmbPermiso.setDisabled(true);
                                cmbPermiso.setValue('');
                                btnAgregarPermiso.setDisabled(false);
                                nombreEstacion.setValue('');
                                nombreEstacion.setDisabled(true);
                                nombreEstacion.allowBlank = false;
                                tienePerm.setDisabled(true);
                            }else{
                                Ext.Msg.wait('<center>Cargando Información, Espere un momento</center>','<center>Mensaje de Sistema</center>');

                                nombreEstacion.setEditable(true);
                                nombreEstacion.setDisabled(false);
                                nombreEstacion.allowBlank = false;
                                nombreEstacion.setValue('');
                                var store = Ext.getStore('mangueras.comboPermisosStore');
                                store.load({
                                    params:{
                                        planta_id: planta_id
                                    },callback:function(){
                                        //                                 nombreEstacion.setDisabled(false);
                                        tienePerm.setDisabled(false);
                                        nombreEstacion.allowBlank = false;
                                        cmbPermiso.setStore(store);
                                        btnAgregarPermiso.setDisabled(true);
                                        cmbPermiso.setDisabled(false);
                                        cmbPermiso.allowBlank = false;
                                        Ext.Msg.hide();
                                    }
                                });
                            }
                        });
                    }
                }catch(Exception){
                    Ext.Msg.hide(
                    null,
                    function(){
                        Ext.MessageBox.show({
                            title: '<center>Mensaje de Sistema</center>',
                            msg: Exception,
                            closable:false,
                            buttons: Ext.Msg.OK,
                            buttonText:{ok:"Aceptar"},
                            icon: Ext.Msg.ERROR
                        });
                    }
                    );
                }
            },
            failure:function(response){
                Ext.MessageBox.show({
                    title: '<center>Mensaje de Sistema</center>',
                    msg: '<center>Fallo la conexión al servidor!</center>',
                    icon: Ext.MessageBox.ERROR,
                    buttons: Ext.Msg.OK,
                    buttonText:{ok:"Aceptar"},
                    closable:false
                });
            }
        });

        this.getView().down('#txtDescripcion').setValue('');
    },

    onTxtPermisoFocusleave: function(component, event, eOpts) {
        // this.getView().down('#txtDescripcion').setValue('');
        // var cmbPlaza = this.getView().down('#cmbPlaza').getValue(),
        //     cmbClave = this.getView().down('#cmbClave').selection.data.cvecia,
        //     permiso = this.getView().down('#txtPermisoManguera'),
        //     value = component.value,
        //     btnAgregarPermiso = this.getView().down('#btnAddPermiso');

        // Ext.Msg.wait('<center>Cargando Información, Espere un momento</center>','<center>Mensaje de Sistema</center>');
        // Ext.Ajax.request({
        //     url: 'api/Mangueras/searchPermiso',
        //     params:{
        //         plaza_id : cmbPlaza,
        //         cvecia: cmbClave,
        //         permiso: value
        //     },
        //     headers:{
        //         Accept: 'application/json, */*'
        //     },
        //     success:function(response){
        //         try{
        //             var resp = JSON.parse(response.responseText);
        //             Ext.Msg.hide();
        //             if(resp.success){
        //                 console.log(resp);
        //             }else{
        //                 Ext.Msg.confirm('Mensaje de Sistema','¿Quiere agregar un permiso?',function(btn){
        //                     if(btn === 'yes'){
        //                         permiso.setValue('');
        //                         btnAgregarPermiso.setDisabled(false);
        //                     }else{
        //                         permiso.markInvalid('No existe el permiso en la información seleccionada, agregue el permiso o verifique porfavor!');
        //                         btnAgregarPermiso.setDisabled(true);
        //                     }
        //                 });
        //             }
        //         }catch(Exception){
        //             Ext.Msg.hide(
        //                 null,
        //                 function(){
        //                     Ext.MessageBox.show({
        //                         title: '<center>Mensaje de Sistema</center>',
        //                         msg: Exception,
        //                         closable:false,
        //                         buttons: Ext.Msg.OK,
        //                         buttonText:{ok:"Aceptar"},
        //                         icon: Ext.Msg.ERROR
        //                     });
        //                 }
        //             );
        //         }
        //     },
        //     failure:function(response){
        //         Ext.MessageBox.show({
        //             title: '<center>Mensaje de Sistema</center>',
        //             msg: '<center>Fallo la conexión al servidor!</center>',
        //             icon: Ext.MessageBox.ERROR,
        //             buttons: Ext.Msg.OK,
        //             buttonText:{ok:"Aceptar"},
        //             closable:false
        //         });
        //     }
        // });
    },

    onBtnAddPermisoClick: function(button, e, eOpts) {
        var window = this;
        Ext.Msg.wait('<center>Cargando Información, Espere un momento</center>','<center>Mensaje de Sistema</center>');
        var ventana = Ext.create('widget.windownewpermisos');

        var nombrePlanta = this.getView().down('#cmbPlanta').rawValue,
            planta_id = this.getView().down('#cmbPlanta').getValue(),
            clave = this.getView().down('#cmbClave').selection.data.cvecia,
            plaza_id = this.getView().down('#cmbPlaza').getValue(),
            num_estacion = this.getView().down('#txtNumEstacion').getValue(),
            rubroVenta = this.getView().down('#cmbCanalVenta').getValue(),
            plaza = this.getView().down('#cmbPlaza').selection.data.plaza;

        if(rubroVenta == 4){
            ventana.down('#txtPlaza_id').setValue(plaza_id);
            ventana.down('#txtNumEsta').setValue(num_estacion);
            //     ventana.down('#txtPlantaId').setValue(planta_id);
            ventana.down('#txtCvecia').setValue(clave);
            ventana.down('#txtPlaza').setValue(plaza);
        }else if(rubroVenta == 2){
            ventana.down('#txtPlaza_id').setValue(plaza_id);
            ventana.down('#txtEstacionPlanta').setValue(nombrePlanta);
            ventana.down('#txtNumEsta').setValue(num_estacion);
            ventana.down('#txtEstacionPlanta').setEditable(false);
            ventana.down('#txtPlantaId').setValue(planta_id);
            ventana.down('#txtCvecia').setValue(clave);
            ventana.down('#txtPlaza').setValue(plaza);
        }
        ventana.down('#txtEstaPlanta').setValue(rubroVenta);

        Ext.Msg.hide();
        ventana.show();
    },

    onTxtNumBasculaChange: function(field, newValue, oldValue, eOpts) {
        this.getView().down('#txtNumEco').setValue('');
        this.getView().down('#txtNumRed').setValue('');
        this.getView().down('#txtSubRed').setValue('');
        this.getView().down('#txtNumBomba').setValue('');
        this.getView().down('#txtNumEstacion').setValue('');
        this.getView().down('#cmbPermisoManguera').setValue('');
        this.getView().down('#cmbPermisoManguera').allowBlank = true;
        this.getView().down('#txtNombreEstacion').setValue('');
        this.getView().down('#txtNombreEstacion').setDisabled(true);
        this.getView().down('#txtNombreEstacion').allowBlank = true;
        this.getView().down('#btnAddPermiso').setDisabled(true);
        this.getView().down('#btnAddPermiso').allowBlank = true;
        // this.getView().down('#descripcion').setHidden(false);
        this.getView().down('#txtDescripcion').setDisabled(false);
        // this.getView().down('#descripcion1').setHidden(true);
        this.getView().down('#text1').setValue('');
        this.getView().down('#num1').setValue('');
        this.getView().down('#text2').setValue('');
        this.getView().down('#num2').setValue('');
        this.getView().down('#txtDescripcion').setValue('Bascula '+newValue);
    },

    onTxtNumRedChange: function(field, newValue, oldValue, eOpts) {
        this.getView().down('#txtNumBascula').setValue('');
        this.getView().down('#txtNumEco').setValue('');
        this.getView().down('#txtNumBomba').setValue('');
        this.getView().down('#txtNumEstacion').setValue('');
        this.getView().down('#cmbPermisoManguera').setValue('');
        this.getView().down('#cmbPermisoManguera').allowBlank = true;
        this.getView().down('#btnAddPermiso').setDisabled(true);
        this.getView().down('#txtNombreEstacion').setValue('');
        this.getView().down('#txtNombreEstacion').setDisabled(true);
        this.getView().down('#txtNombreEstacion').allowBlank = true;
        // this.getView().down('#btnAddPermisoManguera').allowBlank = true;
    },

    onTxtSubRedChange: function(field, newValue, oldValue, eOpts) {
        this.getView().down('#cmbPermisoManguera').setValue('');
        this.getView().down('#cmbPermisoManguera').allowBlank = true;
        this.getView().down('#btnAddPermiso').setDisabled(true);
        this.getView().down('#btnAddPermiso').allowBlank = true;
        var num_red = this.getView().down('#txtNumRed').getValue();
        this.getView().down('#txtDescripcion').setValue('');
        this.getView().down('#text1').setValue('Red ');
        this.getView().down('#num1').setValue(num_red);
        this.getView().down('#text2').setValue('Sub_red ');
        this.getView().down('#num2').setValue(newValue);
        this.getView().down('#txtNombreEstacion').setValue('');
        this.getView().down('#txtNombreEstacion').setDisabled(true);
        this.getView().down('#txtNombreEstacion').allowBlank = true;
        // this.getView().down('#descripcion').setValue('Red '+num_red+', Sub_red '+ newValue);
    },

    onTxtNumBombaChange: function(field, newValue, oldValue, eOpts) {
        this.getView().down('#txtNumBascula').setValue('');
        this.getView().down('#txtNumRed').setValue('');
        this.getView().down('#txtSubRed').setValue('');
        this.getView().down('#txtNumEco').setValue('');
        // this.getView().down('#descripcion').setDisabled(false);
        // this.getView().down('#descripcion1').setHidden(false);
        this.getView().down('#txtDescripcion').setValue('');
        this.getView().down('#text1').setValue('Dispensario ');
        this.getView().down('#num1').setValue(newValue.substring(0,1));
        this.getView().down('#text2').setValue('Bomba ');
        this.getView().down('#num2').setValue(newValue);
        // this.getView().down('#txtNombreEstacion').setValue('');
        // this.getView().down('#txtNombreEstacion').setDisabled(true);
        // this.getView().down('#txtNombreEstacion').allowBlank = true;
        // this.getView().down('#cmbPermisoManguera').setValue('');
        // this.getView().down('#cmbPermisoManguera').allowBlank = true;
        // this.getView().down('#descripcion').setValue('Dispensario '+newValue.substring(0,1)+', Bomba '+newValue);
    },

    onBtnGuardarClick: function(button, e, eOpts) {
        var win =  button.up('window'),
            form   = win.down('form'),
            record = form.getRecord(),
            values = form.getValues();

        var records = [];

        var desc = this.getView().down('#descripcion1'),
            txt1 = this.getView().down('#text1').getValue(),
            num1 = this.getView().down('#num1').getValue(),
            txt2 = this.getView().down('#text2').getValue(),
            num2 = this.getView().down('#num2').getValue(),
            descripcion = txt1.concat(' '+num1+', '+txt2+' '+num2);

        Ext.each(desc.items.items,function(child){
            if(child.value !== ""){
                values['descrip_manguera'] = descripcion;
            }
        });

        var plaza = this.getView().down('#cmbPlaza').selection.data.plaza,
            nombre_plaza = this.getView().down('#cmbPlaza').rawValue,
            plaza_id = this.getView().down('#cmbPlaza').getValue(),
            rubro_venta = this.getView().down('#cmbCanalVenta').selection.data.rubro_venta,
            rubro_venta_id = this.getView().down('#cmbCanalVenta').getValue(),
            descrip_rubro_venta = this.getView().down('#cmbCanalVenta').rawValue,
            planta = this.getView().down('#cmbPlanta').rawValue,
            num_manguera = this.getView().down('#id_manguera').getValue(),
            clave = this.getView().down('#cmbClave').selection.data.cvecia;

        var store = Ext.getStore('mangueras.PermisosStore').data.items;

        if(form.isValid()){
            Ext.Msg.wait('<center>Procesando Información, Espere un momento</center>','<center>Mensaje de Sistema</center>');
            if (store != ""){
                var json = "";
                Ext.Array.each(store, function(data,i){
                    if(Ext.isEmpty(json)){
                        json = Ext.JSON.encode(data.data);
                    }else{
                        json +=','+Ext.JSON.encode(data.data);
                    }
                });

                values['plaza'] = plaza;
                values['descrip_rubro_venta'] = descrip_rubro_venta;
                values['rubro_venta'] = rubro_venta;
                values['nombre_planta'] = planta;
                values['cvecia'] = clave;

                Ext.Ajax.request({
                    url:'api/Mangueras/insert',
                    timeout:600000,
                    params:{
                        info: json,
                        records: Ext.JSON.encode(values)
                    },
                    success:function(response){
                        try{
                            var resp = JSON.parse(response.responseText);
                            Ext.Msg.hide();
                            if(resp.success){
                                Ext.MessageBox.show({
                                    title: '<center>Mensaje de Sistema</center>',
                                    msg: resp.message,
                                    icon: Ext.MessageBox.INFO,
                                    buttons: Ext.Msg.OK,
                                    buttonText:{ok:"Aceptar"},
                                    closable:false
                                });
                                win.close();
                                var sto = Ext.getStore('mangueras.ManguerasStore');
                                sto.add({
                                    plazas: nombre_plaza,
                                    descrip_rubro_venta: descrip_rubro_venta,
                                    num_manguera: num_manguera,
                                    descrip_manguera: values.descrip_manguera,
                                    num_bascula: values.num_bascula,
                                    num_bomba: values.num_bomba,
                                    num_eco: values.num_eco,
                                    num_estacion: values.num_estacion,
                                    num_red: values.num_red,
                                    sub_red: values.sub_red,
                                    tiene_perm:1,
                                    id:1
                                });

                                Ext.getStore('mangueras.PermisosStore').removeAll();
                            }else{
                                Ext.Msg.hide();
                                Ext.MessageBox.show({
                                    title: '<center>Mensaje de Sistema</center>',
                                    msg: resp.message,
                                    icon: Ext.MessageBox.ERROR,
                                    buttons: Ext.Msg.OK,
                                    buttonText:{ok:"Aceptar"},
                                    closable:false
                                });
                            }
                        }catch(Exception){
                            Ext.Msg.hide(
                            null,
                            function(){
                                Ext.MessageBox.show({
                                    title: '<center>Mensaje de Sistema</center>',
                                    msg: Exception,
                                    closable:false,
                                    buttons: Ext.Msg.OK,
                                    buttonText:{ok:"Aceptar"},
                                    icon: Ext.Msg.ERROR
                                });
                            }
                            );
                        }
                    },
                    failure:function(error){
                        Ext.MessageBox.show({
                            title: '<center>Mensaje de Sistema</center>',
                            msg: '<center>Fallo la conexión al servidor</center>',
                            icon: Ext.MessageBox.ERROR,
                            buttons: Ext.Msg.OK,
                            buttonText:{ok:"Aceptar"},
                            closable:false
                        });
                    }
                });
            }else{
                var permiso_id = this.getView().down('#cmbPermisoManguera').getValue(),
                    tiene_perm = this.getView().down('#txtTienePerm').getValue();
                var record = Ext.create('Entregas100Web.model.mangueras.PlazasModel');
                record.set(values);
                record.set('plazas', nombre_plaza);
                record.set('plaza', plaza);
                record.set('permiso_id', permiso_id);
                record.set('descrip_rubro_venta', descrip_rubro_venta);
                record.set('rubro_venta', rubro_venta);
                record.set('tiene_perm',0);
                record.set('nombre_planta',planta);
                record.set('cvecia', clave);
                window.store = store;
                var store = Ext.getStore('mangueras.ManguerasStore');
                store.add(record);
                if(store.needsSync){
                    store.sync({
                        success: function(batch,options){
                            onSyncSucess();
                            Ext.MessageBox.show({
                                title: '<center>Mensaje de Sistema</center>',
                                msg: '<center>Se agrego correctamente!</center>',
                                closable:false,
                                buttons: Ext.Msg.OK,
                                buttonText:{ok:"Aceptar"},
                                icon: Ext.MessageBox.INFO
                            });

                        },
                        failure:function(batch){
                            store.rejectChanges();
                            Ext.each(batch.exceptions, function(operation){
                                if(operation.error.statusText === ""){
                                    Ext.Msg.hide();
                                    Ext.MessageBox.show({
                                        title: '<center>Mensaje de Sistema</center>',
                                        msg: '<center>Fallo la conexión con el servidor!</center>',
                                        closable:false,
                                        buttons: Ext.Msg.OK,
                                        buttonText:{ok:"Aceptar"},
                                        icon: Ext.Msg.ERROR
                                    });
                                }else{
                                    Ext.Msg.hide();
                                    var error = batch.getExceptions();
                                    var error1 = error[0].getError();
                                    Ext.MessageBox.show({
                                        title: '<center>Mensaje de Sistema</center>',
                                        msg: '<center>'+error1+'</center>',
                                        closable:false,
                                        buttons: Ext.Msg.OK,
                                        buttonText:{ok:"Aceptar"},
                                        icon: Ext.Msg.ERROR
                                    });
                                }
                            });
                        }
                    });
                }else{
                    onSyncSucess();
                }
            }
        }else{
            Ext.MessageBox.show({
                title: '<center>Mensaje de Sistema</center>',
                msg: '<center>¡Captura los campos que son requeridos!</center>',
                closable:false,
                buttons: Ext.Msg.OK,
                buttonText:{ok:"Aceptar"},
                icon: Ext.Msg.ERROR
            });
        }

        function onSyncSucess() {
            Ext.Msg.hide();
            win.close();
        }
    },

    onBtnSalirClick: function(button, e, eOpts) {
        this.view.close();
    }

});
