/*
 * File: app/view/ZonasPanel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.view.ZonasPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.zonaspanel',

    requires: [
        'Entregas100Web.view.ZonasPanelViewModel',
        'Entregas100Web.view.ZonasPanelViewController',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.filters.filter.String',
        'Ext.grid.filters.filter.List',
        'Ext.grid.column.Boolean',
        'Ext.grid.filters.filter.Boolean',
        'Ext.view.Table',
        'Ext.grid.column.Action',
        'Ext.grid.filters.Filters'
    ],

    controller: 'zonaspanel',
    viewModel: {
        type: 'zonaspanel'
    },
    id: 'zonasPanel',
    closable: true,
    glyph: 'f041@FontAwesome',
    title: 'Zonas',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            ui: 'footer',
            items: [
                {
                    xtype: 'button',
                    itemId: 'btnRefrescar',
                    ui: 'default-small',
                    glyph: 'f021@FontAwesome',
                    text: 'Refrescar',
                    listeners: {
                        click: 'onBtnRefrescarClick'
                    }
                },
                {
                    xtype: 'button',
                    permissionId: 5,
                    itemId: 'btnAgregar',
                    glyph: 'f055@FontAwesome',
                    text: 'Agregar',
                    listeners: {
                        click: 'onBtnAgregarClick'
                    }
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            showMenuTriggers: true,
            showMenuHint: true,
            flex: 1,
            itemId: 'zonasGrid',
            scrollable: true,
            autoLoad: true,
            columnLines: true,
            enableColumnHide: false,
            enableColumnMove: false,
            bind: {
                store: '{ZonasLocalStore}'
            },
            columns: [
                {
                    xtype: 'numbercolumn',
                    width: 80,
                    dataIndex: 'zona',
                    text: 'Zona',
                    format: '0,000',
                    filter: {
                        type: 'string'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    width: 300,
                    dataIndex: 'descripcion',
                    text: 'Descripción',
                    filter: {
                        type: 'string'
                    }
                },
                {
                    xtype: 'gridcolumn',
                    width: 150,
                    dataIndex: 'nombre_plaza',
                    text: 'Plaza',
                    filter: {
                        type: 'list'
                    }
                },
                {
                    xtype: 'booleancolumn',
                    width: 150,
                    dataIndex: 'ayudante',
                    text: 'Requiere ayudante',
                    falseText: 'NO',
                    trueText: 'SI',
                    undefinedText: 'DESCONOCIDO',
                    filter: {
                        type: 'boolean'
                    }
                },
                {
                    xtype: 'actioncolumn',
                    permissionId: 6,
                    width: 30,
                    items: [
                        {
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                var editarZonaWindow = Ext.create("Entregas100Web.view.EditarZonaWindow");

                                editarZonaWindow.down("form").loadRecord(record);
                                editarZonaWindow.show();
                            },
                            icon: 'resources/icon/editar.png',
                            tooltip: 'Editar'
                        }
                    ]
                }
            ],
            viewConfig: {
                emptyText: 'No se encontraron resultados'
            },
            plugins: [
                {
                    ptype: 'gridfilters'
                }
            ]
        }
    ]

});