/*
 * File: app/model/CombinacionFormaPerfilModel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.model.CombinacionFormaPerfilModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String',
        'Ext.data.field.Boolean'
    ],

    fields: [
        {
            type: 'int',
            name: 'id'
        },
        {
            type: 'int',
            name: 'tipo_cliente_id'
        },
        {
            type: 'string',
            name: 'tipo_cliente'
        },
        {
            type: 'int',
            name: 'forma_pago_id'
        },
        {
            type: 'string',
            name: 'forma_pago'
        },
        {
            type: 'boolean',
            name: 'es_default'
        }
    ]
});