/*
 * File: app/model/HorarioZonaModel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.model.HorarioZonaModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.Date',
        'Ext.data.field.String'
    ],

    fields: [
        {
            type: 'int',
            name: 'id'
        },
        {
            type: 'int',
            name: 'zona_id'
        },
        {
            type: 'date',
            name: 'hora_inicial',
            dateFormat: 'H:i:s'
        },
        {
            type: 'date',
            name: 'hora_final',
            dateFormat: 'H:i:s'
        },
        {
            type: 'int',
            name: 'zona'
        },
        {
            type: 'int',
            name: 'plaza_id'
        },
        {
            type: 'string',
            name: 'plaza'
        }
    ]
});