/*
 * File: app/model/OperadorModel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.model.OperadorModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String',
        'Ext.data.field.Boolean',
        'Ext.data.field.Date'
    ],

    fields: [
        {
            type: 'int',
            name: 'id'
        },
        {
            type: 'string',
            name: 'nombre'
        },
        {
            type: 'string',
            name: 'nip'
        },
        {
            type: 'int',
            name: 'tipo_usuario_id'
        },
        {
            type: 'int',
            name: 'plaza_id'
        },
        {
            type: 'boolean',
            name: 'estatus'
        },
        {
            type: 'boolean',
            name: 'sesion'
        },
        {
            type: 'int',
            name: 'unidad_id'
        },
        {
            type: 'boolean',
            name: 'plazas'
        },
        {
            type: 'date',
            name: 'fecha_sesion',
            dateFormat: 'Y-m-d H:i:s'
        },
        {
            type: 'date',
            name: 'fecha_registro',
            dateFormat: 'Y-m-d H:i:s'
        },
        {
            type: 'string',
            name: 'tipo_usuario'
        }
    ]
});