/*
 * File: app/model/ScriptRemoto.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.model.ScriptRemoto', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Integer',
        'Ext.data.field.Date'
    ],

    idProperty: 'pathname',

    fields: [
        {
            type: 'string',
            allowNull: true,
            name: 'filename'
        },
        {
            type: 'int',
            allowNull: true,
            name: 'size'
        },
        {
            type: 'date',
            allowNull: true,
            name: 'last_modified',
            dateFormat: 'U'
        },
        {
            type: 'string',
            allowNull: true,
            name: 'content'
        },
        {
            type: 'string',
            allowNull: true,
            name: 'pathname'
        }
    ]
});