/*
 * File: app/controller/StoreController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.controller.StoreController', {
    extend: 'Ext.app.Controller',

    onStoreAjaxException: function(proxy, response, operation, eOpts, store) {
        var me = this,
            message;

        // mensaje de error
        if (typeof operation.error === "string") {
            message = operation.error;
        } else {
            message = operation.error.status + " " + operation.error.statusText + ". " + operation.error.response.responseText;
        }

        console.log(store.isSyncing);

        // muestra el mensaje de error
        Ext.Msg.show({
            title: 'Mensaje del Sistema',
            message: message,
            icon: Ext.Msg.ERROR,
            buttons: Ext.Msg.OK
        });
    }

});
