/*
 * File: app/model/mangueras/ManguerasModel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Entregas100Web.model.mangueras.ManguerasModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    idProperty: 'id_manguera',

    fields: [
        {
            name: 'plazas'
        },
        {
            name: 'rubro_venta'
        },
        {
            name: 'descrip_rubro_venta'
        },
        {
            name: 'num_manguera'
        },
        {
            name: 'descrip_manguera'
        },
        {
            name: 'num_eco'
        },
        {
            name: 'num_bascula'
        },
        {
            name: 'num_red'
        },
        {
            name: 'num_bomba'
        },
        {
            name: 'nombre_planta'
        },
        {
            name: 'num_estacion'
        },
        {
            name: 'sub_red'
        },
        {
            name: 'tiene_perm'
        },
        {
            name: 'plaza'
        }
    ]
});